### ISSUE TITLE
C2 appears to work backwards if the z carriage is too high

### ISSUE THREAD

**Issue by RobMackie** [FabMo/FabMo-Engine#1010]
If the z carriage is more than 3/4 of the way up, but not activating the z limit switch, c2 does not work. It seems to probe upwards for the limit switch and then never tries for the touch plate and reports that it didn't find the touch plate, and asks if you started above the limit switch.

**Comment by kyle-kingsbury** [comment]
C3 seems to work fine when it is probing for Z and it does so in a very similar way.

**Comment by kyle-kingsbury** [comment]
Fixed with https://github.com/FabMo/FabMo-Engine/pull/1068
