### ISSUE TITLE
C3 moves away from home unnecessarily

### ISSUE THREAD

**Issue by RobMackie** [FabMo/FabMo-Engine#1011]
C3 moves away from the origin, even if no limit switch is active. It should only back off if a limit switch is active. As is, it sometimes crashes hard into the back,right and top physical limits for no reason at all. 

The logic might better be "check for limit switches", if none rise to z limit and back off, then go to x limit and back off then go to y limit and backoff.

Only if the first "check for limit switches detects a switch, should it risk crashing by backing off in an arbitrary direction.

**Comment by kyle-kingsbury** [comment]
Fixed with https://github.com/FabMo/FabMo-Engine/pull/1032.
