### ISSUE TITLE
C2 does a little dance unnecessarily

### ISSUE THREAD

**Issue by RobMackie** [FabMo/FabMo-Engine#1012]
At the end of a c2 on fabmo the bit does a vertical "dance" to show that it is done. This can break a bit (happened to me). It is unnecessary and can cause problems. When c2 is done, it should just stop in place. If it must "dance" (it doesnt' need to), then it should retract up and down, not dance down and then up - but that has it's own problems.)

So let's have it just stop.

**Comment by kyle-kingsbury** [comment]
Fixed with https://github.com/FabMo/FabMo-Engine/pull/1032.
