### ISSUE TITLE
Moves on Axes A-C not going to the correct location

### ISSUE THREAD

**Issue by gordonab** [FabMo/FabMo-Engine#102]
X,Y&Z moves work well, but moving A,B or C from the Editor using OpenSBP don't go to the correct location or don't move at all. This log is an X move to 2 followed by an A move to 2. The works, but the A goes to 0.079.

info: dispatching a chunk: N0G1X2.00000F360.00000 [sbp]
g2: --G-1429643751502----> N0G1X2.00000F360.00000 [g2]
g2: <-C--1429643751515---- {"r":{},"f":[1,0,22]} [g2]
Calling timeout function
debug: Doing the outermost end. [sbp]
info: Got a machine state change: idle [machine]
g2: <-C--1429643751772---- {"sr":{"posx":1.013,"vel":11.02,"stat":5}} [g2]
g2: <-C--1429643752044---- {"sr":{"posx":1.135,"vel":47.15}} [g2]
g2: <-C--1429643752304---- {"sr":{"posx":1.395,"vel":69.48}} [g2]
g2: <-C--1429643752560---- {"sr":{"posx":1.690,"vel":66.68}} [g2]
g2: <-C--1429643752808---- {"sr":{"posx":1.917,"vel":36.66}} [g2]
g2: <-C--1429643753067---- {"sr":{"posx":1.996,"vel":4.83}} [g2]
g2: <-C--1429643753293---- {"sr":{"posx":2.000,"vel":0.00,"stat":3}} [g2]
debug: _setupTransforms [sbp]
debug: _setupTransforms: [{"x":0,"y":0,"z":0},{"x":8,"y":0,"z":0.1},{"x":8,"y":6,"z":0.2},{"x":0,"y":6,"z":0.1}] [sbp]
info: Setting the running state [sbp]
info: Got a machine state change: running [machine]
debug: Evaluating arguments: MA,[2] [sbp]
debug: Taking the users argument: 2 [sbp]
debug: Scrubbed arguments: [2] [sbp]
debug: Evaluating expression: 2 [sbp]
debug:   Evaluating value: 2 [sbp]
debug:   Evaluated 2 as 2 [sbp]
debug:  MA args: [2] [sbp]r MA With arguments: [2] [sbp]
debug: Rotate: {"apply":true,"angle":0,"x":0,"y":0} [sbp]
debug: ShearX: {"apply":true,"angle":0} [sbp]
debug: ShearY: {"apply":true,"angle":0} [sbp]
debug: Scale: {"apply":true,"scalex":1,"scaley":1,"x":0,"y":0} [sbp]
debug: Move: {"apply":true,"x":0,"y":0,"z":0} [sbp]
info: Program over. (pc = 2) [sbp]
info: dispatching a chunk: N0G1A2.00000F360.00000 [sbp]
g2: --G-1429643764219----> N0G1A2.00000F360.00000 [g2]
g2: <-C--1429643764230---- {"r":{},"f":[1,0,22]} [g2]
debug: Doing the outermost end. [sbp]
g2: --G-1429643764322----> M30 [g2]
g2: <-C--1429643764353---- {"r":{},"f":[1,201,3]} [g2]
error: 201,STAT_MINIMUM_LENGTH_MOVE,move is less than minimum length [machine]
error: 201,STAT_MINIMUM_LENGTH_MOVE,move is less than minimum length [machine]
g2: <-C--1429643764733---- {"sr":{"posa":0.078,"vel":0.95}} [g2]":5}} [g2]
g2: <-C--1429643765001---- {"sr":{"posa":0.079,"vel":0.00,"stat":4}} [g2]

**Comment by ryansturmer** [comment]
@aldenhart or @giseburt Can you guys comment on this?  Initially, I think we'd just like the option to use the accessory axes as additional cartesian axes - but shortly after for rotary indexing, 5-axis operation etc.  It should be configurable - whats the state of things with the current build of the firmware?
