### ISSUE TITLE
Input "stop" during a probe causes hang

### ISSUE THREAD

**Issue by kyle-kingsbury** [FabMo/FabMo-Engine#1028]
This persists back to at least:

Software Version
3.1.42-dev
G2 Firmware Version
101.57.43

**Comment by RobMackie** [comment]
This was done using the same input for probe and stop.  Needs to be tested with probe and stop on different inputs.

**Comment by kyle-kingsbury** [comment]
Fixed with https://github.com/FabMo/FabMo-Engine/pull/1111
