### ISSUE TITLE
Dimmed area in main menu is weird and should feel bad about itself.

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#113]
When the right side DRO menu is displayed, the main UI is "dimmed" such that any click in the main UI dismisses the DRO.  When the main menu is visible, the dimming doesn't go all the way to the bottom of the page, which looks weird, and doesn't quite work the way we intend:

![screenshot_2015-04-30-16-54-29](https://cloud.githubusercontent.com/assets/1383181/7430769/5e505d56-efe5-11e4-8755-0ff826a4c7af.png)

Screenshot thanks to @tedh-shopbot

**Comment by wholetthedogsout** [comment]
This looks closed

**Comment by ryansturmer** [comment]
Still happens on my android device.

**Comment by wholetthedogsout** [comment]
Sorry this is fixed on the branch I made a pull request for. Would you like to me to merge them?

**Comment by ryansturmer** [comment]
Yes by all means!  Don't break the build ;)
