### ISSUE TITLE
Current position variables( i.e., cmd_posx) not updating correctly after using handwheel or this.cmd_posx is broken

### ISSUE THREAD

**Issue by gordonab** [FabMo/FabMo-Engine#138]
This was discovered while moving the tool to start position of a CC circle using the handwheel. The tool first moves to the position of the tool before moving with the handwheel and executes the circle from that position.

**Comment by ryansturmer** [comment]
Can you provide the detailed sequence of steps?  Was the CC issued from the editor?

Also:  Do you get the same behavior if you move to position using the editor (in g-code mode) and then issuing a CC?

**Comment by ryansturmer** [comment]
Is this still an issue, or resolved?
