### ISSUE TITLE
Units on handwheel

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#148]
Units should be displayed on the handwheel, and should be changeable.

**Comment by wholetthedogsout** [comment]
@ryansturmer little confused how you imagine this. You want units on the actual wheel or a drop down to change units where it says inches?

**Comment by ryansturmer** [comment]
See current version of the handwheel.  The units are displayed (speed units, so in/sec) and the default system units can be displayed on the configuration page.
