### ISSUE TITLE
Add inch/metric button

### ISSUE THREAD

**Issue by jw4rd** [FabMo/FabMo-Engine#155]
and/or add support for g20/g21 in SBP files

**Comment by ryansturmer** [comment]
Thank you for using the issue tracker.

Inch/metric button is a good idea.  You can do G20/G21 through the editor, but there's an equivalent sbp command - @gordonab can you tell us what it is?

**Comment by gordonab** [comment]
VD,,<units:0=inches,1=mm>

This OpenSBP command changes the units with G20 or G21, but does nothing
with any of the displayed info in the Dashboard or previewer.

On Thu, Sep 3, 2015 at 12:13 PM, Ryan Sturmer <notifications@github.com>
wrote:

> Thank you for using the issue tracker.
>
> Inch/metric button is a good idea. You can do G20/G21 through the editor,
> but there's an equivalent sbp command - @gordonab
> <https://github.com/gordonab> can you tell us what it is?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FabMo/FabMo-Engine/issues/155#issuecomment-137499063>.
>



-- 
Gordon Bergfors

Wake Forest, NC

**Comment by ryansturmer** [comment]
both VD and G20/G21 will now work to switch units.  There is a "system default units" configuration option in the config page as of 8287110 that lets you set what the engine defaults to.  You can change units at any time with the above mentioned commands, but to make it stick, you have to set it in the configuration settings.
