### ISSUE TITLE
Handwheel jog feedrate very slow when using metric

### ISSUE THREAD

**Issue by jw4rd** [FabMo/FabMo-Engine#158]

**Comment by ryansturmer** [comment]
The handwheel units don't actually change, the behavior *should* be:

1. Units displayed on the wheel itself
2. Speeds scaled accordingly with units (1.0 in/sec should be converted to the equivalent speed when you switch to millimeters)

**Comment by ryansturmer** [comment]
Resolved in a recent commit.  Handwheel displays and honors both unit systems.  (And has been moved to per-minute rather than per-second)
