### ISSUE TITLE
SBP code does not run from editor

### ISSUE THREAD

**Issue by jw4rd** [FabMo/FabMo-Engine#159]

**Comment by gordonab** [comment]
What kind of commands are you attempting to execute? Can you send some examples for me to investigate?

**Comment by jw4rd** [comment]
these are the commands I tried to execute from the editor
VD,,1
M2,1,1

**Comment by ryansturmer** [comment]
Do you have the editor set to OpenSBP mode?

**Comment by gordonab** [comment]
At the end of the day, I had trouble as well with VD and setting to mm. It
appears to be locking something up. I'll troubleshoot it further first
thing in the morning.

**Comment by ryansturmer** [comment]
Were you having trouble with both VD and G20/21? Or just VD?

The switch to millimeters mode does work (in g-code at least) but the units on the display do not update accordingly.  We can fix this pretty easily.

**Comment by jw4rd** [comment]
I did not have a problem executing g20/21

**Comment by jw4rd** [comment]
I did not have a problem executing g20/21

**Comment by ryansturmer** [comment]
Fixed in d6a5732736b8e2d764ab9c33e5091883b9f70286 - this was an issue with the way the OpenSBP runtime interpreted state transitions from G2, specifically how it handles G-Code programs that contain no motion commands (For instance a program containing only a single G20/G21)
