### ISSUE TITLE
G-Code programs that do not set the tool in motion do not manage state properly

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#16]
If a g-code program (or direct string) is issued that does not cause the tool to change 'stat' - the tool never leaves the 'running' state, which causes it to misbehave (requiring a /quit from the API) to be back in a "good" state.

**Comment by jlucidar** [comment]
I run this gcode file :
```
G90
G91
G92
```
And the machine went back to its idle state as it should .
I close the issue.
