### ISSUE TITLE
X, Y, and Z zero buttons not working correctly after "G21" or "VD,,1" (metric) codes

### ISSUE THREAD

**Issue by jw4rd** [FabMo/FabMo-Engine#160]
orange buttons in FabMo jog/DRO keypad

**Comment by ryansturmer** [comment]
I have observed this as well.  This is to do with the machine offsets, and how zeroes are computed.

**Comment by ryansturmer** [comment]
This is resolved by commit 2343deb1c75005fd650853c9b1af15caa1662e4d
