### ISSUE TITLE
Changing GUN to 1 in g2.json is not being read at initialization

### ISSUE THREAD

**Issue by gordonab** [FabMo/FabMo-Engine#161]
Even though GUN is changed in G2.json G2 is starting up in G20 mode and not G21.

info: Configuring G2... [engine]
debug: Configuring driver... [g2_config]
g2: --C-1441379330729----> ♦ [g2]
g2: --G-1441379330729----> {clr:n} [g2]
g2: --G-1441379330729----> M30 [g2]
g2: --G-1441379330729----> G20 [g2]
g2: --G-1441379330745----> M30 [g2]
...

**Comment by ryansturmer** [comment]
GUN actually is not doing anything for us in G2 json.  If we want to change the **current** working coordinate system, we need to issue a G20 or G21 (As is done at g2 startup) - I have extracted this in 8287110 and placed it in a machine global configuration, and added that configuration to the configuration tree and configuration page app.
