### ISSUE TITLE
Add axis direction to configuration

### ISSUE THREAD

**Issue by jw4rd** [FabMo/FabMo-Engine#168]
independent direction control for each axis

**Comment by ryansturmer** [comment]
This is already available!

In the Configuration page under "Channels" you can change the sign of the "Travel per Rotation" figure.  (Don't change the value, just negate it)

![screen shot 2015-09-09 at 9 30 00 am](https://cloud.githubusercontent.com/assets/1383181/9763101/a880a9a6-56d5-11e5-89d1-06586f268a08.png)
