### ISSUE TITLE
With 6 characters axis will wrap to next row in DRO table.

### ISSUE THREAD

**Issue by wholetthedogsout** [FabMo/FabMo-Engine#170]
Not sure if this is a common scenario. 
<img width="329" alt="screen shot 2015-09-09 at 11 16 30 am" src="https://cloud.githubusercontent.com/assets/8646647/9766040/10e0b04a-56e5-11e5-9591-fb4257632018.png">

**Comment by wholetthedogsout** [comment]
Sorry 7 characters.

**Comment by ryansturmer** [comment]
This still happens, but now the number of decimal places when running in millimeters mode is reduced, making it unlikely.

**Comment by gordonab** [comment]
This could still be a problem in Inch mode with a large machine. It isn't that uncommon to have a 3 figure number with 3 decimal places and a sign. For instance, the longest machines we make are 288" long.

**Comment by gordonab** [comment]
I would expect 8 characters, including the sign and decimal point with be enough for most coordinates. The exception will be with rotary axes, they can go into 5 or 6 digits. It would make sense to limit the degree display to 2 decimal places and 6 digits for a total of 10 characters.

**Comment by jlucidar** [comment]
We probably also need at least 6 digit for the metric system ( something
like xxxx.xx mm is totally possible on big machines... )
