### ISSUE TITLE
App gap on firefox

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#171]
The apps container frame seems to suffer some sort of weird gap (firefox only)

Firefox:

![screen shot 2015-09-09 at 1 06 56 pm](https://cloud.githubusercontent.com/assets/1383181/9768896/aadcc7d8-56f4-11e5-99ae-c9104ff3265f.png)

Chrome:

![screen shot 2015-09-09 at 1 14 23 pm](https://cloud.githubusercontent.com/assets/1383181/9768903/b65ef4fa-56f4-11e5-9fcc-f33960794a4b.png)

**Comment by wholetthedogsout** [comment]
Thought it was the css not being normalized, but that wasn't it, but was able to fix it another way.
