### ISSUE TITLE
Default units display broken in chrome

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#172]
Weirdness in chrome (Mac OS X) in the "Configuration" app

![screen shot 2015-09-09 at 1 16 35 pm](https://cloud.githubusercontent.com/assets/1383181/9768951/0dc86550-56f5-11e5-9b74-fd943f5afd03.png)

**Comment by wholetthedogsout** [comment]
issue here is the normalize.css and the foundation frame work weren't playing nicely, so just had to reverse the order they were linked.
