### ISSUE TITLE
gcode 'm8' not working in the editor 

### ISSUE THREAD

**Issue by jw4rd** [FabMo/FabMo-Engine#175]
and spindle turns off without an 'm8'
this program turns on the router for one second and turns off without 'm8':
m4
g4p1

**Comment by ryansturmer** [comment]
The spindle is only allowed to run during a machining cycle.  It turns off automatically when your program is over. This is behaving as intended.

**Comment by jw4rd** [comment]
What if you need to turn the router off to do a tool change or some other operation?
m4
g4p1
m8
g4p1
m4
g4p1

**Comment by ryansturmer** [comment]
I think we're talking about two separate issues here.

Are you saying that M8 doesn't actually turn the spindle off when in a machining cycle?  Or are you saying that the spindle turns off by itself at the end of a cycle?  Or are both occurring?

M8 should not be required to turn off the spindle at the end of a file.  It *should* work however, to turn the spindle off during a file.

**Comment by ryansturmer** [comment]
Woops!

It's M5 to stop the spindle, not M8.  Give that a try :walking:

**Comment by jw4rd** [comment]
That works.  Thanks.
