### ISSUE TITLE
Download file in Job Manager History

### ISSUE THREAD

**Issue by jw4rd** [FabMo/FabMo-Engine#176]
After clicking 'download file' and then clicking the 'home' icon, the downloaded file is still shown in the window.  Add a menu button or back button after downloading a file in the history?

**Comment by ryansturmer** [comment]
I'm not sure I follow.  When you click "download file" does it not download it to your downloads folder?

**Comment by jw4rd** [comment]
No, it does not download the file.  The gcode is just displayed in a window when I click download.
I'm using firefox and ubuntu.

**Comment by eliwilliams** [comment]
This issue has been partially resolved - downloading works for Chrome and Safari currently, but not for Firefox.

**Comment by wholetthedogsout** [comment]
I get a part extension when downloading in firefox, not sure why the download is being interrupted, could be security setting?

**Comment by eliwilliams** [comment]
This is what's happening to me too. What you'll see is that the part extension actually contains all of the data of the download. If you open the download link in a new tab, the download actually finishes.
