### ISSUE TITLE
master branch does not contain all app files?

### ISSUE THREAD

**Issue by ril3y** [FabMo/FabMo-Engine#194]
Hey guys I have Fabmo up and running on the rpi / ubuntu / osx and noticed that they do not have all the cool apps that some of the older branch had.  Is this intentional?

**Comment by ryansturmer** [comment]
Yes.  The system does not ship with apps.  There are a few offerings here:

https://github.com/FabMo/fabmo-example-app
https://github.com/FabMo/fabmo-txtmaker-app
https://github.com/FabMo/fabmo-sb4-app
https://github.com/FabMo/fabmo-touchandgo-app
https://github.com/FabMo/fabmo-spoilboarder-app
https://github.com/FabMo/fabmo-partmaker-app
https://github.com/ryansturmer/fabmo-terrainman-app

**Comment by ril3y** [comment]
Thanks ryan!
