### ISSUE TITLE
Better interaction for pulling out DRO / left side menu

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#225]
Swipe out would be nice (hamburger is confusing) - maybe a pull-tab?

**Comment by wholetthedogsout** [comment]
Given some thought to this, still don't have a good answer.

**Comment by ryansturmer** [comment]
Sounds like we're going to try a tab, since we're removing it from the bottom bar?

**Comment by wlyoung** [comment]
Yesterday when we first hooked up the Fabmo board, neither James or I could
get the left menu flyout to appear on our phones...I'm android and he's
IPhone. After about 10-15 minutes the left flyout appeared on both of our
phones, seemingly instantaneously?

On Wed, Nov 4, 2015 at 9:25 AM, Ryan Sturmer <notifications@github.com>
wrote:

> Sounds like we're going to try a tab, since we're removing it from the
> bottom bar?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FabMo/FabMo-Engine/issues/225#issuecomment-153740384>.
>



-- 
www.shopbottools.com
www.100kgarages.com
Cell: (757) 999-5592

**Comment by ryansturmer** [comment]
I'm going to close this for now.  I think we're sticking with the current look for the time being.
