### ISSUE TITLE
Progress bar immediately goes to full with no % number next to it in desktop mode.

### ISSUE THREAD

**Issue by gordonab** [FabMo/FabMo-Engine#233]

**Comment by ryansturmer** [comment]
Can you post the file you ran?

**Comment by wholetthedogsout** [comment]
In the bottom bar?

**Comment by gordonab** [comment]
Yes, the progress indicator in the bottom bar. The file was the sblogo.
I'll attach the file when I get to the office.

**Comment by gordonab** [comment]
This is the file I ran when the progress bar went to full and didn't display the percentage.
 
[shopbot_logo.sbp.txt](https://github.com/FabMo/FabMo-Engine/files/14134/shopbot_logo.sbp.txt)

**Comment by ryansturmer** [comment]
Only the bottom bar progress indicator?  Or the one in the DRO as well?

**Comment by gordonab** [comment]
Both of them are showing full the next time a file is run.

**Comment by ryansturmer** [comment]
Having a hard time reproducing - is this a file that's run to completion before the next one starts?  Is any progress indicated during the run?  Or is it just stuck at 100% - Also what is your engine version (http://tool_url/version)

**Comment by gordonab** [comment]
Both progress bars immediately go to full when starting the SB Logo file as
soon as the file starts. It can be a file that is resubmitted and run to
completion or a new file.

info: G2 Firmware Build: 83.09 [engine]

So far this is the only edison I have with the new image. I will try
another one shortly and see if it behaves the same way.

On Thu, Oct 15, 2015 at 4:08 PM, Ryan Sturmer <notifications@github.com>
wrote:

> Having a hard time reproducing - is this a file that's run to completion
> before the next one starts? Is any progress indicated during the run? Or is
> it just stuck at 100% - Also what is your engine version (
> http://tool_url/version)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FabMo/FabMo-Engine/issues/233#issuecomment-148506855>.
>



-- 
Gordon Bergfors

Wake Forest, NC

**Comment by ryansturmer** [comment]
Sorry Gordon, not the firmware version, but the engine version:  Visit http://192.168.1.x/version - With your IP subbed in

**Comment by gordonab** [comment]
Tried this, but get "The page at /version was not found."

On Thu, Oct 15, 2015 at 4:56 PM, Ryan Sturmer <notifications@github.com>
wrote:

> Sorry Gordon, not the firmware version, but the engine version: Visit
> http://192.168.1.x/version - With your IP subbed in
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FabMo/FabMo-Engine/issues/233#issuecomment-148519052>.
>



-- 
Gordon Bergfors

Wake Forest, NC

**Comment by ryansturmer** [comment]
Sorry, did you include the :9876 ?  If you don't have that page, you're probably using a pretty dated version of the engine somehow, which is worrisome if it's a new image.

**Comment by gordonab** [comment]
From 192.168.1.200:9876/version :

{"status":"success","data":{"version":""}}


On Thu, Oct 15, 2015 at 5:26 PM, Ryan Sturmer <notifications@github.com>
wrote:

> Sorry, did you include the :9876 ? If you don't have that page, you're
> probably using a pretty dated version of the engine somehow, which is
> worrisome if it's a new image.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FabMo/FabMo-Engine/issues/233#issuecomment-148525548>.
>



-- 
Gordon Bergfors

Wake Forest, NC

**Comment by gordonab** [comment]
I just imaged another and it had the same empty version

**Comment by ryansturmer** [comment]
Hmm, that's not necessarily am old version it might be related to the git issue you saw the other day

**Comment by ryansturmer** [comment]
Yep, it was an old version on the image that was non-updatable.  This has been resolved in some recent commits.
