### ISSUE TITLE
Auto discovery not working when UDP broadcast forbidden or port blocked

### ISSUE THREAD

**Issue by gordonab** [FabMo/FabMo-Engine#247]
There is now a DeskTop in the shop on the shopbot-private network. I can access fabmo over the network, but finding it was a chore. The FabMo Tool Minder doesn't see it and Fing shows it as device from Murata Manufacturing without an SSID name. The address is normal for our network, but a little different than those on the famo network, 192.168.33.78 is the current IP address.

**Comment by jlucidar** [comment]
Do you have any ideo on how solving this ? is there some magical network protocol that will do the job ?

**Comment by jlucidar** [comment]
this is now improved by bonjour support. closing.
