### ISSUE TITLE
No support for TR command

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#249]

**Comment by gordonab** [comment]
Are you ready to work on the modbus connection to the VFD?

**Comment by ryansturmer** [comment]
Mainly I wanted this not to crash the tool.  There is no VFDs on handibot so the answer to that is no, for now.  Turns out, this command wasn't what was crashing it, TR commands are ignored (just like any other unknown command) which I think is the correct course of action for now.
