### ISSUE TITLE
Fabmo doesn't see my wifi network

### ISSUE THREAD

**Issue by wlyoung** [FabMo/FabMo-Engine#256]
In the WIFI network list Fabmo only shows one network that is at a local business. It doesn't list my network at all which is in the same room. Broadcast SSID is turned on and it has the same network  security setting as the one it sees.

**Comment by ryansturmer** [comment]
Can you try to reboot and reconnect to the tool a few times in AP mode and see if the network list changes at all?

**Comment by wlyoung** [comment]
We've rebooted everything we could think of, multiple times No love so far.

On Fri, Nov 13, 2015 at 2:48 PM, Ryan Sturmer <notifications@github.com>
wrote:

> Can you try to reboot and reconnect to the tool a few times in AP mode and
> see if the network list changes at all?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FabMo/FabMo-Engine/issues/256#issuecomment-156539786>.
>



-- 
www.shopbottools.com
www.100kgarages.com
Cell: (757) 999-5592

**Comment by wlyoung** [comment]
My local network just appeared...not sure what changed? How do we connect
to it and input the wifi password?

On Fri, Nov 13, 2015 at 3:35 PM, Bill Young <wlyoung@gmail.com> wrote:

> We've rebooted everything we could think of, multiple times No love so far.
>
> On Fri, Nov 13, 2015 at 2:48 PM, Ryan Sturmer <notifications@github.com>
> wrote:
>
>> Can you try to reboot and reconnect to the tool a few times in AP mode
>> and see if the network list changes at all?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/FabMo/FabMo-Engine/issues/256#issuecomment-156539786>
>> .
>>
>
>
>
> --
> www.shopbottools.com
> www.100kgarages.com
> Cell: (757) 999-5592
>
>


-- 
www.shopbottools.com
www.100kgarages.com
Cell: (757) 999-5592

**Comment by ryansturmer** [comment]
Double click the network name, and input the key in the dialog.   The network appearing is luck-of-the-draw - I need to make the scans more aggressive.  Did it ever show more than one network in the list? Or did your network turn up alone?

**Comment by wlyoung** [comment]
When my network finally showed up it was in addition to the other
network...they both showed at the same time.

Brian, James, and I tried clicking everything we could click yesterday but
no luck with entering the password. This morning my network showed up when
I first turned it on and I let it run while I had my first cup of coffee.
After reading your email I went back and double clicked the network name
and was able to enter the password and connect just fine. Don't know if we
just hadn't found the right clicking spot yesterday, or if it needed to run
for a while?

All seems to be working now and connected to my local network

On Fri, Nov 13, 2015 at 5:10 PM, Ryan Sturmer <notifications@github.com>
wrote:

> Double click the network name, and input the key in the dialog. The
> network appearing is luck-of-the-draw - I need to make the scans more
> aggressive. Did it ever show more than one network in the list? Or did your
> network turn up alone?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FabMo/FabMo-Engine/issues/256#issuecomment-156572870>.
>



-- 
www.shopbottools.com
www.100kgarages.com
Cell: (757) 999-5592

**Comment by wlyoung** [comment]
Just to put a point on this, once I got everything figured out the network
stuff has worked great. I've turned my router off and on, changed
passwords, and changed SSID. It would fall back into direct connect like it
was supposed to and then connect when the network was up.

Just as an fyi though, the double tap to get the password entry form is not
intuitive on a phone

On Sat, Nov 14, 2015, 7:52 AM Bill Young <wlyoung@gmail.com> wrote:

> When my network finally showed up it was in addition to the other
> network...they both showed at the same time.
>
> Brian, James, and I tried clicking everything we could click yesterday but
> no luck with entering the password. This morning my network showed up when
> I first turned it on and I let it run while I had my first cup of coffee.
> After reading your email I went back and double clicked the network name
> and was able to enter the password and connect just fine. Don't know if we
> just hadn't found the right clicking spot yesterday, or if it needed to run
> for a while?
>
> All seems to be working now and connected to my local network
>
> On Fri, Nov 13, 2015 at 5:10 PM, Ryan Sturmer <notifications@github.com>
> wrote:
>
>> Double click the network name, and input the key in the dialog. The
>> network appearing is luck-of-the-draw - I need to make the scans more
>> aggressive. Did it ever show more than one network in the list? Or did your
>> network turn up alone?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/FabMo/FabMo-Engine/issues/256#issuecomment-156572870>
>> .
>>
>
>
>
> --
> www.shopbottools.com
> www.100kgarages.com
> Cell: (757) 999-5592
>
> --

Bill Young

mobile 757-999-5592
office  888-680-4800 ext 133

**Comment by ryansturmer** [comment]
The double tap is a vestige of an older interface and will be fixed.  Closing this for now.
