### ISSUE TITLE
executing a file from the editor doesn't seem to work for me

### ISSUE THREAD

**Issue by wlyoung** [FabMo/FabMo-Engine#258]
This may be an sbp/gcode issue, but if I type a ShopBot command like MX,6 into the editor and try to run it using any of the execute options, nothing happens. The same with the Macro editor...I can't run a macro from any of the execute menu items when I'm in the macro editor, but it will run from the list of macros if I click the Run/Play triangle dohickey.

**Comment by ryansturmer** [comment]
Are you selecting the language from the language menu?

**Comment by wlyoung** [comment]
Obviously not! Works now


On Mon, Nov 16, 2015 at 11:04 AM, Ryan Sturmer <notifications@github.com>
wrote:

> Are you selecting the language from the language menu?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FabMo/FabMo-Engine/issues/258#issuecomment-157081139>.
>



-- 
www.shopbottools.com
www.100kgarages.com
Cell: (757) 999-5592

**Comment by ryansturmer** [comment]
The language selection should "stick" so you don't have to do it every time (except with the macro editor, which will get fixed)  - remember, you can Ctrl+Enter to run quickly, if you're on a PC
