### ISSUE TITLE
g28.3 y0

### ISSUE THREAD

**Issue by jw4rd** [FabMo/FabMo-Engine#260]
sets y = -0.02

**Comment by ryansturmer** [comment]
Check your G55 offsets - they are more than likely set to something nonzero.

**Comment by gordonab** [comment]
The OpenSBP commands I worked on last week should fix this. I will commit them this evening after the changes to the configuration page.

**Comment by gordonab** [comment]
Try the latest commit. Hopefully this fixes this issue.

**Comment by jw4rd** [comment]
fabmoDashboard.runSBP("Z3")
works
