### ISSUE TITLE
Create new macro

### ISSUE THREAD

**Issue by Ryan-Patterson** [FabMo/FabMo-Engine#263]
I am unable to create a new macro.  I do not have any macros in the list and when I click create macro nothing happens.  I tried from and Android phone and a PC laptop.

**Comment by ryansturmer** [comment]
Right click inside the macro manager and choose "Reload Frame" or "This Frame->Reload" and try again, just in case you are getting an old version of the macro manager.  Do this from the laptop.

**Comment by ryansturmer** [comment]
Also, what browser, on the laptop?

**Comment by Ryan-Patterson** [comment]
The Browser is Chrome this is the first time this laptop was connected to Fabmo.   I am having an issue getting my newest laptop to connect.

**Comment by Ryan-Patterson** [comment]
I tried the reload frame.  Also tried Chrome, FireFox and IE.  IE did not display correctly at all.

**Comment by ryansturmer** [comment]
IE is not supported.  I am looking into this.

**Comment by ryansturmer** [comment]
Wait, you've got one laptop that will connect and a new one that doesn't?

**Comment by Ryan-Patterson** [comment]
Yes I started a new issue on the connection.  

I have now tried creating a Macro on a Windows10 tablet and it will not create a new one.  It shows not data available in table.

**Comment by Ryan-Patterson** [comment]
Not sure if this helps but if I go to this page 192.168.42.1:9876/approot/macro_manager.fma/index.html# and click new macro there is a little box that displays briefly it reads something about a call to update macro.

**Comment by ryansturmer** [comment]
Ryan, if you're wanting to provide diagnostic information - visit the macro manager in chrome, and open the developers console (Ctrl+Shift+J) and click "create new macro" and post any messsages that are printed to the console

**Comment by Ryan-Patterson** [comment]
I do not get any messages.  If I refresh the page I get "Websocket connected"

**Comment by ryansturmer** [comment]
If you get the chance to bring your card into the shop - Might be best that I observe the issue myself!
