### ISSUE TITLE
clear queue

### ISSUE THREAD

**Issue by jw4rd** [FabMo/FabMo-Engine#270]
Jobs still appear in the job manager after pressing 'clear queue', but after a page reload the queue is cleared.

**Comment by jw4rd** [comment]
firefox

**Comment by ryansturmer** [comment]
Try this:

1) Delete your /opt/fabmo/approot directory
2) Restart your engine
3) Right click inside the job manager frame and choose "reload frame" or "this frame->reload"

**Comment by ryansturmer** [comment]
Did this fix your issue?

**Comment by jw4rd** [comment]
It is fixed.  Thanks!
