### ISSUE TITLE
Changed name, number and description of macro and none of them persisted

### ISSUE THREAD

**Issue by gordonab** [FabMo/FabMo-Engine#271]

**Comment by ryansturmer** [comment]
Is this still an issue, or did refreshing the macro app take care of it?

**Comment by gordonab** [comment]
Yes, I just tried it on another Fabmo as well and had the same results. The name will still appear right after being changed if I change from the macros app to home or the editor. But, if I edit a macro after changing any of these attributes they are lost when saving the file and returning to the macro app.

**Comment by gordonab** [comment]
It took 2 tries, but now the fabmo on the office DT is reading the header info in the macro files on that edison.
