### ISSUE TITLE
Long load time and incomplete cut

### ISSUE THREAD

**Issue by Ryan-Patterson** [FabMo/FabMo-Engine#273]
I submit the attached file as a job and click to run.  The spindle starts within a couple seconds then movement does not start until after 30 plus seconds.  Then on my card at home the motion will stop a few lines into the file.  Tried same file on Desktop in back the startup is the same but it does rum to completion.  Starting file from Android phone on both controllers.
[Vinyl.txt](https://github.com/FabMo/FabMo-Engine/files/50996/Vinyl.txt)

**Comment by gordonab** [comment]
Runs to completion on the fabmo office DT. It takes about the same amount
of time to load, loading 14722 lines. Did you change the name to Vinyl.sbp
to run it?

On Thu, Dec 3, 2015 at 10:55 AM, Ryan-Patterson <notifications@github.com>
wrote:

> I submit the attached file as a job and click to run. The spindle starts
> within a couple seconds then movement does not start until after 30 plus
> seconds. Then on my card at home the motion will stop a few lines into the
> file. Tried same file on Desktop in back the startup is the same but it
> does rum to completion. Starting file from Android phone on both
> controllers.
> Vinyl.txt <https://github.com/FabMo/FabMo-Engine/files/50996/Vinyl.txt>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FabMo/FabMo-Engine/issues/273>.
>



-- 
Gordon Bergfors

Wake Forest, NC

**Comment by Ryan-Patterson** [comment]
Yes I changed the name to txt to be able to uplaod the file.

**Comment by ryansturmer** [comment]
Ryan, can you post the contents of /opt/fabmo/config/engine.json on your tool?

**Comment by ryansturmer** [comment]
If you have the card with you I can look at it this afternoon, also

**Comment by Ryan-Patterson** [comment]
I have the card at home.

**Comment by ryansturmer** [comment]
The contents of that file, and the contents of the debug log after the file fails will be instructive.

**Comment by ryansturmer** [comment]
Actually, ryan, if you go to your tool url/config and paste the result here - that will save you from having to go fish out that file.

**Comment by Ryan-Patterson** [comment]
Thought it might be my home network so I tried in AP mode and same thing occurs.
I will bring my card in tomorrow.

**Comment by ryansturmer** [comment]
Long load time is fixed in the latest version.  (Print statements in the OpenSBP runtime really slow things down due to writing the journal) - stop in the middle is unexpected though as it doesn't happen on other tools - is it possible that you hit an input switch, or got a spurious input trigger?

-R

**Comment by ryansturmer** [comment]
Updated and retested, seems to be fixed - I think this was a corruption issue that was causing the crash, but will keep an eye on it.
