### ISSUE TITLE
lost connect file still running

### ISSUE THREAD

**Issue by Ryan-Patterson** [FabMo/FabMo-Engine#275]
I am cutting the attached file I wanted to stop the file before it finished.  Opened the browse and all I get if the spinning waiting on Fabmo wheel.
[Words2.txt](https://github.com/FabMo/FabMo-Engine/files/52959/Words2.txt)

**Comment by ryansturmer** [comment]
Lost connections have been improved in the latest version, so I'm closing this, although there's nothing that precludes the file from continuing to run if you disconnect from the tool.... Closing for now, we can reopen if still an issue.
