### ISSUE TITLE
X's over position

### ISSUE THREAD

**Issue by Ryan-Patterson** [FabMo/FabMo-Engine#276]
Every time I refresh the browser the position values are replace with Xs.  Then when I move an axis the display will replace the X's with zeros.
<img width="1022" alt="fabmo" src="https://cloud.githubusercontent.com/assets/16008898/11613574/e8226bd6-9bf3-11e5-90f6-0428415952e5.PNG">

**Comment by ryansturmer** [comment]
Fixed in latest.  Sorry Ryan, I should have sent you home work this....silly glitch.

R
