### ISSUE TITLE
Job Manager cleanup of up-next card

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#295]
Still acts kind of funny - at first load of the page, it often has content that seems to dismiss immediately (should start blank and then get filled in)

On top of that, there is occasional weirdness:

![screen shot 2016-01-04 at 10 58 42 am](https://cloud.githubusercontent.com/assets/1383181/12093681/4d1a0518-b2d2-11e5-921f-4154a9f82ac7.png)

**Comment by wholetthedogsout** [comment]
Working on this now, there was a lot of messy logic to get it to a functional state but doing a lot of house cleaning now

**Comment by wholetthedogsout** [comment]
I think I previously fixed the overlapping text. Do you know what conditions led to this?

**Comment by ryansturmer** [comment]
I haven't seen this in a while, I think it's resolved.
