### ISSUE TITLE
Junction Deviation settings returned as NULL from G2

### ISSUE THREAD

**Issue by gordonab** [FabMo/FabMo-Engine#305]
the junction deviation settings were added to the G2 configuration file. At startup when the settings are initialized G2 is returning a null value and error message. Are these supported by G2 is there an order that these should be sent?

Settings in default file:

    ...
    "xjd": 0.05,
    "yjd": 0.05,
    "zjd": 0.05,
    "ajd": 0.05,
    "bjd": 0.05,
    "cjd": 0.05, 
    ...

Return from G2:

2: <-C--1452519174595---- {"r":{"xjd":null},"f":[1,3,13]} [g2]
rror: 3,STAT_NOOP,function had no [machine]
2: <-C--1452519174626---- {"r":{"yjd":null},"f":[1,3,13]} [g2]
rror: 3,STAT_NOOP,function had no [machine]
2: <-C--1452519174626---- {"r":{"zjd":null},"f":[1,3,13]} [g2]
rror: 3,STAT_NOOP,function had no [machine]
2: <-C--1452519174642---- {"r":{"ajd":null},"f":[1,3,13]} [g2]
rror: 3,STAT_NOOP,function had no [machine]
2: <-C--1452519174642---- {"r":{"bjd":null},"f":[1,3,13]} [g2]
rror: 3,STAT_NOOP,function had no [machine]
2: <-C--1452519174642---- {"r":{"cjd":null},"f":[1,3,13]} [g2]
rror: 3,STAT_NOOP,function had no [machine]

**Comment by ryansturmer** [comment]
xjd is deprecated and no longer used in G2.
