### ISSUE TITLE
Issue with unexpected Z moves in Opensbp file

### ISSUE THREAD

**Issue by wlyoung** [FabMo/FabMo-Engine#308]
The attached zip file should cut a series of triangles in the part, alternating ends. In the ShopBot software it works correctly, but in FabMo it cuts one triangle and then plunges back in the same spot and only cuts part of the second triangle in the pair.

[beam preview](https://cloud.githubusercontent.com/assets/4410233/12355734/aa901064-bb6c-11e5-9609-0a4f8a7bf099.jpg)

[beamer.zip](https://github.com/FabMo/FabMo-Engine/files/92036/beamer.zip)

**Comment by ryansturmer** [comment]
@gordonab I think you fixed this?
