### ISSUE TITLE
Character limit annoyance in DRO "jump to position" feature.

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#333]
To reproduce:

1. Enter 3.500 in one of the position locations
2. Place the curser after the ''5' and type another nonzero digit, such as 3.  

The behavior should be to push out the last zero and enter 3.53, but what it actually does is hit the character limit and refuse to enter a character at all, which is not the expected behavior for most users.

**Comment by wholetthedogsout** [comment]
do you want this behavior to be consistent if the values or not zero? say 3.511 or just if the zeros are filled in?

**Comment by wholetthedogsout** [comment]
I think this is more the behavior you want
