### ISSUE TITLE
Occasionally Modal darkens but no modal is displayed.

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#339]

**Comment by wholetthedogsout** [comment]
Explain more?

**Comment by ryansturmer** [comment]
Sometimes, particuarly after A disconnect, or sometimes after a dismissed modal, I come to the dashboard page and the screen is darkened as if a modal should be displayed, but no modal is visible.  A refresh usually clears it up.  After the refresh, there is no modal or darkened screen.
