### ISSUE TITLE
Inner frame size on previewer not quite right on linux/chrome

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#340]
Scrollbars appear on previewer - seems previewer is slightly larger than the inner frame dimensions.

**Comment by MaxFrenzy** [comment]
Noticed this on windows install (chrome) as well.   Also, when in MM mode, I have to zoom back out quite a bit to get the whole previewer (i.e. all 3 axis) in view. This seems to happen if I'm in MM mode in general or if toggling within the previewer.

**Comment by ryansturmer** [comment]
Hey @MaxFrenzy can you report your software version? (in the top right corner under "configuration")

**Comment by MaxFrenzy** [comment]
@ryansturmer Well at least as far as linux goes (ubuntu), it is software version: ec0f93fdc855-dev. 
There are a variety of other issues that I am experiencing but don't necessarily want to post them as official issues as I am unsure if they are actual bugs, problems with OS/environment, hardware config, etc. I'd like to have a chat with you when you get a chance. -Thanks Matt D.

**Comment by ryansturmer** [comment]
Shoot me an email @MaxFrenzy and we can discuss those other issues.  We're looking at this one now.
