### ISSUE TITLE
Long delay on response to pressing PLAY button when running a large file

### ISSUE THREAD

**Issue by gordonab** [FabMo/FabMo-Engine#344]
When running a large file in the job manager there is a very long delay to any kind of feedback after pressing the PLAY button. It isn't clear whether or not the button press was excepted. The 2.8MB file that I've been running takes almost 2 mins to change to the red STOP button in the Job manager.

**Comment by ryansturmer** [comment]
Closing this as the delay has been substantially reduced.  Will open a separate issue for indicating that the request to run has been made, which is something we've discussed for a lot of activities in the dashboard.
