### ISSUE TITLE
Config/Offset not applied to .nc files

### ISSUE THREAD

**Issue by SW0rden** [FabMo/FabMo-Engine#385]
I forgot that I had offsetting enabled and while trying to figure out why my .sbp file was cutting -2.0" in X, I tried a .nc file and found that g-code files are unaffected by offsetting (preview also).

Offsetting also affects the z-zeroing routine.  This was catching me up a bit too, because of my SB3 conditioning where offsetting is canceled upon completion of the file being run.  This also affects commands in the SB4 app.

**Comment by ryansturmer** [comment]
Scott, what do you mean by "ofsetting enabled?"

**Comment by gordonab** [comment]
If Offset is Enabled in the configuration it won't effect a G-code file when run. Right now the Offset, Scale, Rotate... transformations only apply to OpenSBP code.

**Comment by SW0rden** [comment]
Enabling offset in config will run a file offset from the current 0,0,0 location.  I had done this last week and forgot to 'Disable' it before running a file yesterday.  After Z zeroing with the macro, I couldn't figure out why my z raised to 1.01 each time instead of the commanded final safe z position of 1.0.  I had a x offset of -2 and a z offset of 0.01 that was being applied and didn't realize it until previewing the file as .sbp and .nc and .sbp files will show in preview and run with the offset, but .nc files will not show the offset in preview and they also run without the offset.

![offset](https://cloud.githubusercontent.com/assets/18059548/14115872/962d7b0a-f5a2-11e5-8beb-e1fc6c8831f2.JPG)

**Comment by SW0rden** [comment]
Ok, thanks Gordon, that explains it.

Just a note, the value box labels for rotation, scale, and offset stay as mm when the default unit is set to inch.

**Comment by SW0rden** [comment]
Sorry if I shouldn't have hit "closed".  Not sure of the 'etiquette' here.

**Comment by gordonab** [comment]
I will check on the unit types and make sure they're set up correctly in the html file.

**Comment by ryansturmer** [comment]
Ofsetting is a feature of SBP, and will not work with g-code files.  This is by design.  We will make this clear in the documentation.
