### ISSUE TITLE
Error message in during engine start

### ISSUE THREAD

**Issue by gordonab** [FabMo/FabMo-Engine#389]
info: Got a machine state change: idle [machine]
error: -1,JSON_PARSE_ERROR,Could not parse response: '"hv":0,"id":"0213-0215d403","msg":"SYSTEM READY"},"f":[1,0,1]}' (SyntaxError: Unexpected token :) [machine]
info: Loading the machine configuration... [engine]

**Comment by ryansturmer** [comment]
This one seems to be a windows-node-serialport only
