### ISSUE TITLE
On an android phone the icons for edit and delete are empty boxes

### ISSUE THREAD

**Issue by wlyoung** [FabMo/FabMo-Engine#394]
![empty icons](https://cloud.githubusercontent.com/assets/4410233/14316459/0b514270-fbd1-11e5-8794-d4ca1830991b.png)

**Comment by wholetthedogsout** [comment]
@wlyoung I think this should be fixed on master

**Comment by ryansturmer** [comment]
This is fixed, although the macro manager needs some love (other, unrelated display issues.
