### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#420]
Authentication per the auth branch.

**Comment by ryansturmer** [comment]
Things left to do here:

1. Merge the root endpoint and authentication endpoints so there's no redirecting, etc.
2. Incorporate user account management into the configuration app
3. Protect the new user creation endpoint and remove the button from the sign-in page that creates a new user

**Comment by jlucidar** [comment]
points 2 & 3 are done (see  dc0ece1ee455bbb0386fb66f3e1be16705c20a0c) ! 
How do we want to integrate point n°1 (to replace [that implementation](https://github.com/FabMo/FabMo-Engine/blob/authentication/authentication/authentication.html)) ?  

@wholetthedogsout, @ryansturmer  any idea ??
