### ISSUE TITLE
Reconnection not working properly

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#436]
If you lose contact with a tool, and then the network is restored, the "waiting for fabmo" doesn't go away properly, and sits and spins forever until a refresh.

To reproduce:

1. Start engine
2. Connect to the dashboard from a different computer
3. Disable the network interface on that computer (pull ethernet cable, turn off ethernet interface, disable wifi)
4. Wait for "Waiting for FabMo" spinner
5. Re-enable network
6. Observe that the modal never goes away.  A refresh restores the connection.

@jlucidar can you take a look at this - I believe it to be related to authentication.

**Comment by jlucidar** [comment]
sorry my bad.
