### ISSUE TITLE
Grey box left behind when DRO closes

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#445]
To reproduce (on desktop):

1. Open the dashboard to the homepage, and open any app.
2. Open the DRO
3. Scale the window so it's less than 800px (approx) wide
4. Close the DRO

The space previously occupied by the DRO is not reclaimed when the box is closed.  This seems to happen on tablets too, when you switch landscape/portrait orientation with the DRO open.

**Comment by wholetthedogsout** [comment]
We had a on window resize event, that I took out because it was causing another issue, trying to search for which one it was so I don't reintroduce that one.
