### ISSUE TITLE
On mobile, 'Up Next' controls don't work.

### ISSUE THREAD

**Issue by SW0rden** [FabMo/FabMo-Engine#459]
None of these work on tablet/phone.

![buttons don t work](https://cloud.githubusercontent.com/assets/18059548/16389957/0a2ae4d4-3c66-11e6-9472-c934d4083e54.JPG)

**Comment by wholetthedogsout** [comment]
these should all work now.

**Comment by jlucidar** [comment]
works on my phone...

**Comment by wholetthedogsout** [comment]
cool will close

**Comment by SW0rden** [comment]
Yup, works good now on both for me too.
