### ISSUE TITLE
Problem with ON INPUT statement with no action following it...no GOTO for instance

### ISSUE THREAD

**Issue by wlyoung** [FabMo/FabMo-Engine#472]
If you put something like ON INPUT(3,0) in a macro to prevent multiple triggers, the macro won't run and pushing the green button doesn't register.

**Comment by ryansturmer** [comment]
@wlyoung can you elaborate on this?  What do you mean by prevent multiple triggers?

**Comment by wlyoung** [comment]
In the current ShopBot zeroing routines, after a contact trigger the switches are turned off to avoid extra triggers and bounce-induced problems. Those SO commands with no action step after them...No GOTO for instance.. failed if Authorization is turned on.

**Comment by ryansturmer** [comment]
Resolved as we phase out the ON INPUT command.
