### ISSUE TITLE
Job manager stucks when paused if previous job ends when paused

### ISSUE THREAD

**Issue by Alex-Canales** [FabMo/FabMo-Engine#473]
If you pause a job and at the same moment the job finishes, then when the next job is paused, the buttons "resume" and "quit" will not appear and you will get stuck.

How to reproduce the bug:

Step 1: use this code sample:

```
G0 X1 Y1 Z1
G0 X0 Y0 Z0
```

Step 2: run the job. When the job is nearly done (x, y, z nearly equal to 0), press the stop button. The job should be over with the stop button activated (and the buttons "resume" and "quit" displayed). The buttons "resume" and "quit" disappear automatically.

Step 3: run a new job. Press the stop button. The buttons "resume" and "quit" will not appear and the job manager will be stuck with this job. To stop the problem, you will have to kill the engine and run it again.

Here is the result at step 3.

![stuck](https://cloud.githubusercontent.com/assets/12187544/16566375/0ef8c5fe-4214-11e6-814a-59e4151de1a6.png)

**Comment by Alex-Canales** [comment]
I manage to get stuck by putting two jobs (always the same as in the example) in the queue, launching one, pausing, resuming. When the first one is over, the second one is display as on the previous .screenshot

**Comment by jlucidar** [comment]
OK, I'm trying to reproduce it. just to make sure : Can you copy and paste the log from the engine here ?

**Comment by Alex-Canales** [comment]
Here what is print in the terminal. Two jobs are pending in the queue. The logs are from the moment I run the first job.

    debug: POST /jobs/queue/run [engine]
    info: Running the next job in the queue [routes]
    info: Arming the machine for nextJob [machine]
    info: Firing automatically since authorization is disabled. [machine]
    info: Machine is deauthorized. [machine]
    info: Running next job [machine]
    info: printing[object Object] [db]
    info: 72 [db]
    info: [object Object] [machine]
    info: Running job {"file_id":5,"name":"Less dumb short code","description":"A G-Code job from the editor","created_at":1467799242213,"started_at":1467799259089,"finished_at":null,"state":"running","order":null,"_id":72} [machine]
    info: Running file /opt/fabmo/files/b295c760-42ab-11e6-906b-f9cd58d69b79.nc [machine]
    info: Got a machine state change: idle [machine]
    info: Connected G-Code Runtime [gcode]
    debug: Saving config to /opt/fabmo/config/instance.json [config]
    debug: GET /jobs/queue [engine]
    debug: GET /jobs/queue [engine]
    debug: fsync()ed /opt/fabmo/config/instance.json [config]
    debug: GET /jobs/history?start=0&count=10 [engine]
    info: Got a machine state change: running [machine]
    info: Got a machine state change: paused [machine]
    debug: Saving config to /opt/fabmo/config/instance.json [config]
    debug: fsync()ed /opt/fabmo/config/instance.json [config]
    info: Arming the machine for resume [machine]
    info: Firing automatically since authorization is disabled. [machine]
    info: Machine is deauthorized. [machine]
    info: Got a machine state change: running [machine]
    info: 72 [db]
    info: Setting driver units to INCH [g2]
    debug: GET /jobs/queue [engine]
    debug: GET /jobs/history?start=0&count=10 [engine]
    info: Setting driver units to INCH [g2]
    info: Got a machine state change: idle [machine]
    debug: Saving config to /opt/fabmo/config/instance.json [config]
    debug: fsync()ed /opt/fabmo/config/instance.json [config]
    info: Got a machine state change: idle [machine]
    debug: Saving config to /opt/fabmo/config/instance.json [config]
    debug: fsync()ed /opt/fabmo/config/instance.json [config]
    debug: POST /jobs/queue/run [engine]
    info: Running the next job in the queue [routes]
    info: Arming the machine for nextJob [machine]
    info: Firing automatically since authorization is disabled. [machine]
    info: Machine is deauthorized. [machine]
    info: Running next job [machine]
    info: printing[object Object] [db]
    info: 73 [db]
    info: [object Object] [machine]
    info: Running job {"file_id":5,"name":"Less dumb short code","description":"A G-Code job from the editor","created_at":1467799245346,"started_at":1467799264747,"finished_at":null,"state":"running","order":null,"_id":73} [machine]
    info: Running file /opt/fabmo/files/b295c760-42ab-11e6-906b-f9cd58d69b79.nc [machine]
    debug: GET /jobs/queue [engine]
    debug: GET /jobs/queue [engine]
    debug: GET /jobs/history?start=0&count=10 [engine]

Does the engine generate log files that would me to copy?

**Comment by ryansturmer** [comment]
Alex, can you perform the same test, but turn your log level up to "g2" ?

**Comment by Alex-Canales** [comment]
Here is the logs. As you can see, there is a "no pending job" error. Two jobs are pending in the queue. The logs are from the moment I run the first job.

    debug: POST /jobs/queue/run [engine]
    info: Running the next job in the queue [routes]
    info: Arming the machine for nextJob [machine]
    info: Firing automatically since authorization is disabled. [machine]
    info: Machine is deauthorized. [machine]
    debug: Firing a nextJob [machine]
    info: Running next job [machine]
    info: printing[object Object] [db]
    info: 75 [db]
    info: [object Object] [machine]
    info: Running job {"file_id":5,"name":"Less dumb short code","description":"A G-Code job from the editor","created_at":1467999715411,"started_at":1467999846267,"finished_at":null,"state":"running","order":null,"_id":75} [machine]
    info: Running file /opt/fabmo/files/b295c760-42ab-11e6-906b-f9cd58d69b79.nc [machine]
    info: Got a machine state change: idle [machine]
    g2: --C-1467999846278----> {"mpo":null} [g2]
    info: Connected G-Code Runtime [gcode]
    g2: <-C--1467999846281---- {"r":{"mpo":{"x":0.000,"y":0.000,"z":0.000,"a":0.000,"b":0.000,"c":0.000}},"f":[1,0,13]} [g2]
    debug: Saving config to /opt/fabmo/config/instance.json [config]
    debug: GET /jobs/queue [engine]
    debug: GET /jobs/queue [engine]
    debug: GET /jobs/history?start=0&count=10 [engine]
    g2: --G-1467999846416----> G90
    N1G0 X1 Y1 Z1
    N2G0 X2 Y2 Z2
    N3G0 X0 Y0 Z0
    M30

    M30 [g2]
    debug: fsync()ed /opt/fabmo/config/instance.json [config]
    g2: <-C--1467999846537---- {"sr":{"posx":0.004,"posy":0.004,"posz":0.004,"vel":24.53,"stat":5,"line":1}} [g2]
    info: Got a machine state change: running [machine]
    g2: <-C--1467999846788---- {"sr":{"posx":0.632,"posy":0.632,"posz":0.632,"vel":415.69}} [g2]
    g2: <-C--1467999847039---- {"sr":{"posx":1.626,"posy":1.626,"posz":1.626,"vel":387.88,"line":2}} [g2]
    g2: <-C--1467999847290---- {"sr":{"posx":2.000,"posy":2.000,"posz":2.000,"vel":8.67,"line":3}} [g2]
    g2: <-C--1467999847540---- {"sr":{"posx":1.592,"posy":1.592,"posz":1.592,"vel":395.41}} [g2]
    g2: <-C--1467999847790---- {"sr":{"posx":0.596,"posy":0.596,"posz":0.596,"vel":415.62}} [g2]
    debug: Sending a feedhold [g2]
    g2: --C-1467999847990----> !
     [g2]
    debug: Drained. [g2]
    g2: <-C--1467999848042---- {"sr":{"posx":0.003,"posy":0.003,"posz":0.003,"vel":18.85,"stat":6,"hold":4}} [g2]
    info: Got a machine state change: paused [machine]
    g2: --C-1467999848043----> {"mpo":null} [g2]
    g2: <-C--1467999848054---- {"r":{"mpo":{"x":0.002,"y":0.002,"z":0.002,"a":0.000,"b":0.000,"c":0.000}},"f":[1,0,13]} [g2]
    debug: Saving config to /opt/fabmo/config/instance.json [config]
    g2: <-C--1467999848096---- {"er":{"fb":89.02,"st":94,"msg":"Planner assertion failure - zero length line in calculate trapezoid"}} [g2]
    g2: <-C--1467999848096---- {"er":{"fb":89.02,"st":94,"msg":"Planner assertion failure - zero length move in exec_aline"}} [g2]
    debug: fsync()ed /opt/fabmo/config/instance.json [config]
    g2: <-C--1467999848288---- {"sr":{"posx":0.000,"posy":0.000,"posz":0.000,"vel":0.00,"hold":7}} [g2]
    info: Arming the machine for resume [machine]
    info: Firing automatically since authorization is disabled. [machine]
    info: Machine is deauthorized. [machine]
    debug: Firing a resume [machine]
    g2: --C-1467999850405----> ~ [g2]
    g2: <-C--1467999850407---- {"sr":{"stat":4,"hold":0,"line":0}} [g2]
    info: 75 [db]
    info: Setting driver units to INCH [g2]
    g2: --C-1467999850411----> {"gun":0} [g2]
    g2: <-C--1467999850413---- {"r":{"gun":0},"f":[1,0,10]} [g2]
    g2: --G-1467999850413----> G20
    M30 [g2]
    debug: GET /jobs/queue [engine]
    debug: GET /jobs/history?start=0&count=10 [engine]
    g2: <-C--1467999850663---- {"sr":{"stat":4,"unit":0}} [g2]
    info: Setting driver units to INCH [g2]
    g2: --C-1467999850664----> {"gun":0} [g2]
    info: Got a machine state change: idle [machine]
    g2: --C-1467999850665----> {"mpo":null} [g2]
    g2: <-C--1467999850666---- {"r":{"gun":0},"f":[1,0,10]} [g2]
    g2: --G-1467999850666----> G20
    M30 [g2]
    g2: <-C--1467999850668---- {"r":{"mpo":{"x":0.000,"y":0.000,"z":0.000,"a":0.000,"b":0.000,"c":0.000}},"f":[1,0,13]} [g2]
    debug: Saving config to /opt/fabmo/config/instance.json [config]
    debug: fsync()ed /opt/fabmo/config/instance.json [config]
    g2: <-C--1467999850915---- {"sr":{"stat":4}} [g2]
    info: Got a machine state change: idle [machine]
    g2: --C-1467999850916----> {"mpo":null} [g2]
    g2: <-C--1467999850919---- {"r":{"mpo":{"x":0.000,"y":0.000,"z":0.000,"a":0.000,"b":0.000,"c":0.000}},"f":[1,0,13]} [g2]
    debug: Saving config to /opt/fabmo/config/instance.json [config]
    debug: fsync()ed /opt/fabmo/config/instance.json [config]
    g2: <-C--1467999851169---- {"sr":{"stat":4}} [g2]
    debug: POST /jobs/queue/run [engine]
    info: Running the next job in the queue [routes]
    info: Arming the machine for nextJob [machine]
    info: Firing automatically since authorization is disabled. [machine]
    info: Machine is deauthorized. [machine]
    debug: Firing a nextJob [machine]
    info: Running next job [machine]
    info: printing[object Object] [db]
    info: 76 [db]
    info: [object Object] [machine]
    info: Running job {"file_id":5,"name":"Less dumb short code","description":"A G-Code job from the editor","created_at":1467999717979,"started_at":1467999852233,"finished_at":null,"state":"running","order":null,"_id":76} [machine]
    info: Running file /opt/fabmo/files/b295c760-42ab-11e6-906b-f9cd58d69b79.nc [machine]
    g2: --G-1467999852240----> G90
    N1G0 X1 Y1 Z1
    N2G0 X2 Y2 Z2
    N3G0 X0 Y0 Z0
    M30

    M30 [g2]
    debug: GET /jobs/queue [engine]
    debug: GET /jobs/queue [engine]
    debug: GET /jobs/history?start=0&count=10 [engine]
    debug: POST /jobs/queue/run [engine]
    info: Running the next job in the queue [routes]
    error: Error: No pending jobs.
        at Machine.<anonymous> (/home/alex/Shopbot/Engine/machine.js:607:13)
        at /home/alex/Shopbot/Engine/node_modules/tingodb/lib/tcursor.js:305:4
        at _fnApply (/home/alex/Shopbot/Engine/node_modules/safe/lib/safe.js:172:22)
        at _catcher (/home/alex/Shopbot/Engine/node_modules/safe/lib/safe.js:349:11)
        at /home/alex/Shopbot/Engine/node_modules/safe/lib/safe.js:462:4
        at _wrapArgsSure (/home/alex/Shopbot/Engine/node_modules/safe/lib/safe.js:203:15)
        at Object.async.eachSeries (/home/alex/Shopbot/Engine/node_modules/tingodb/node_modules/async/lib/async.js:142:20)
        at /home/alex/Shopbot/Engine/node_modules/tingodb/lib/tcursor.js:298:9
        at _fnApply (/home/alex/Shopbot/Engine/node_modules/safe/lib/safe.js:172:22)
        at _catcher (/home/alex/Shopbot/Engine/node_modules/safe/lib/safe.js:349:11)
        at /home/alex/Shopbot/Engine/node_modules/safe/lib/safe.js:462:4
        at _wrapArgsSure (/home/alex/Shopbot/Engine/node_modules/safe/lib/safe.js:218:14)
        at Immediate._onImmediate (/home/alex/Shopbot/Engine/node_modules/safe/lib/safe.js:272:23)
        at tryOnImmediate (timers.js:543:15)
        at processImmediate [as _immediateCallback] (timers.js:523:5) [routes]
    debug: GET /jobs/queue [engine]
    g2: <-C--1467999852498---- {"sr":{"posx":0.008,"posy":0.008,"posz":0.008,"vel":12.07,"stat":4,"line":1}} [g2]
    g2: <-C--1467999852749---- {"sr":{"posx":0.046,"posy":0.046,"posz":0.046,"vel":16.37,"stat":4}} [g2]
    g2: <-C--1467999852998---- {"sr":{"posx":0.086,"posy":0.086,"posz":0.086,"stat":4}} [g2]
    g2: <-C--1467999853250---- {"sr":{"posx":0.125,"posy":0.125,"posz":0.125,"stat":4}} [g2]
    g2: <-C--1467999853501---- {"sr":{"posx":0.165,"posy":0.165,"posz":0.165,"stat":4}} [g2]
    g2: <-C--1467999853752---- {"sr":{"posx":0.204,"posy":0.204,"posz":0.204,"stat":4}} [g2]
    g2: <-C--1467999854003---- {"sr":{"posx":0.244,"posy":0.244,"posz":0.244,"stat":4}} [g2]
    g2: <-C--1467999854253---- {"sr":{"posx":0.283,"posy":0.283,"posz":0.283,"stat":4}} [g2]
    g2: <-C--1467999854505---- {"sr":{"posx":0.322,"posy":0.322,"posz":0.322,"stat":4}} [g2]
    g2: <-C--1467999854756---- {"sr":{"posx":0.362,"posy":0.362,"posz":0.362,"stat":4}} [g2]
    g2: <-C--1467999855007---- {"sr":{"posx":0.402,"posy":0.402,"posz":0.402,"stat":4}} [g2]
    g2: <-C--1467999855258---- {"sr":{"posx":0.441,"posy":0.441,"posz":0.441,"stat":4}} [g2]
    g2: <-C--1467999855508---- {"sr":{"posx":0.480,"posy":0.480,"posz":0.480,"stat":4}} [g2]
    g2: <-C--1467999855760---- {"sr":{"posx":0.520,"posy":0.520,"posz":0.520,"stat":4}} [g2]
    g2: <-C--1467999856012---- {"sr":{"posx":0.560,"posy":0.560,"posz":0.560,"stat":4}} [g2]
    g2: <-C--1467999856262---- {"sr":{"posx":0.599,"posy":0.599,"posz":0.599,"stat":4}} [g2]
    g2: <-C--1467999856513---- {"sr":{"posx":0.638,"posy":0.638,"posz":0.638,"stat":4}} [g2]
    g2: <-C--1467999856763---- {"sr":{"posx":0.678,"posy":0.678,"posz":0.678,"stat":4}} [g2]
    g2: <-C--1467999857014---- {"sr":{"posx":0.717,"posy":0.717,"posz":0.717,"stat":4}} [g2]
    g2: <-C--1467999857265---- {"sr":{"posx":0.757,"posy":0.757,"posz":0.757,"stat":4}} [g2]
    g2: <-C--1467999857516---- {"sr":{"posx":0.796,"posy":0.796,"posz":0.796,"stat":4}} [g2]
    g2: <-C--1467999857767---- {"sr":{"posx":0.836,"posy":0.836,"posz":0.836,"stat":4}} [g2]
    g2: <-C--1467999858019---- {"sr":{"posx":0.875,"posy":0.875,"posz":0.875,"stat":4}} [g2]
    g2: <-C--1467999858269---- {"sr":{"posx":0.915,"posy":0.915,"posz":0.915,"stat":4}} [g2]
    g2: <-C--1467999858520---- {"sr":{"posx":0.954,"posy":0.954,"posz":0.954,"stat":4}} [g2]
    g2: <-C--1467999858771---- {"sr":{"posx":0.994,"posy":0.994,"posz":0.994,"stat":4}} [g2]
    g2: <-C--1467999859023---- {"sr":{"posx":1.033,"posy":1.033,"posz":1.033,"stat":4,"line":2}} [g2]
    g2: <-C--1467999859274---- {"sr":{"posx":1.073,"posy":1.073,"posz":1.073,"stat":4}} [g2]
    g2: <-C--1467999859526---- {"sr":{"posx":1.112,"posy":1.112,"posz":1.112,"stat":4}} [g2]
    g2: <-C--1467999859777---- {"sr":{"posx":1.152,"posy":1.152,"posz":1.152,"stat":4}} [g2]
    g2: <-C--1467999860029---- {"sr":{"posx":1.192,"posy":1.192,"posz":1.192,"stat":4}} [g2]
    g2: <-C--1467999860279---- {"sr":{"posx":1.231,"posy":1.231,"posz":1.231,"stat":4}} [g2]
    g2: <-C--1467999860530---- {"sr":{"posx":1.270,"posy":1.270,"posz":1.270,"stat":4}} [g2]
    g2: <-C--1467999860781---- {"sr":{"posx":1.310,"posy":1.310,"posz":1.310,"stat":4}} [g2]
    g2: <-C--1467999861032---- {"sr":{"posx":1.349,"posy":1.349,"posz":1.349,"stat":4}} [g2]
    g2: <-C--1467999861284---- {"sr":{"posx":1.389,"posy":1.389,"posz":1.389,"stat":4}} [g2]
    g2: <-C--1467999861534---- {"sr":{"posx":1.428,"posy":1.429,"posz":1.429,"stat":4}} [g2]
    g2: <-C--1467999861785---- {"sr":{"posx":1.468,"posy":1.468,"posz":1.468,"stat":4}} [g2]
    g2: <-C--1467999862036---- {"sr":{"posx":1.507,"posy":1.507,"posz":1.507,"stat":4}} [g2]
    g2: <-C--1467999862287---- {"sr":{"posx":1.547,"posy":1.547,"posz":1.547,"stat":4}} [g2]
    g2: <-C--1467999862539---- {"sr":{"posx":1.587,"posy":1.587,"posz":1.587,"stat":4}} [g2]
    g2: <-C--1467999862791---- {"sr":{"posx":1.626,"posy":1.626,"posz":1.626,"stat":4}} [g2]
    g2: <-C--1467999863042---- {"sr":{"posx":1.666,"posy":1.666,"posz":1.666,"stat":4}} [g2]
    g2: <-C--1467999863294---- {"sr":{"posx":1.705,"posy":1.705,"posz":1.705,"stat":4}} [g2]
    g2: <-C--1467999863544---- {"sr":{"posx":1.745,"posy":1.745,"posz":1.745,"stat":4}} [g2]
    g2: <-C--1467999863795---- {"sr":{"posx":1.784,"posy":1.784,"posz":1.784,"stat":4}} [g2]
    g2: <-C--1467999864046---- {"sr":{"posx":1.824,"posy":1.824,"posz":1.824,"stat":4}} [g2]
    g2: <-C--1467999864298---- {"sr":{"posx":1.863,"posy":1.863,"posz":1.863,"stat":4}} [g2]
    g2: <-C--1467999864549---- {"sr":{"posx":1.903,"posy":1.903,"posz":1.903,"stat":4}} [g2]
    g2: <-C--1467999864799---- {"sr":{"posx":1.942,"posy":1.942,"posz":1.942,"stat":4}} [g2]
    g2: <-C--1467999865051---- {"sr":{"posx":1.982,"posy":1.982,"posz":1.982,"vel":16.04,"stat":4}} [g2]
    g2: <-C--1467999865302---- {"sr":{"posx":2.000,"posy":2.000,"posz":2.000,"vel":0.38,"stat":4}} [g2]
    g2: <-C--1467999865554---- {"sr":{"posx":1.987,"posy":1.987,"posz":1.987,"vel":14.43,"stat":4,"line":3}} [g2]
    g2: <-C--1467999865805---- {"sr":{"posx":1.948,"posy":1.948,"posz":1.948,"vel":16.37,"stat":4}} [g2]
    g2: <-C--1467999866056---- {"sr":{"posx":1.908,"posy":1.908,"posz":1.908,"stat":4}} [g2]
    g2: <-C--1467999866307---- {"sr":{"posx":1.869,"posy":1.869,"posz":1.869,"stat":4}} [g2]
    g2: <-C--1467999866559---- {"sr":{"posx":1.829,"posy":1.829,"posz":1.829,"stat":4}} [g2]
    g2: <-C--1467999866810---- {"sr":{"posx":1.790,"posy":1.790,"posz":1.790,"stat":4}} [g2]
    g2: <-C--1467999867062---- {"sr":{"posx":1.750,"posy":1.750,"posz":1.750,"stat":4}} [g2]
    g2: <-C--1467999867314---- {"sr":{"posx":1.711,"posy":1.711,"posz":1.711,"stat":4}} [g2]
    g2: <-C--1467999867565---- {"sr":{"posx":1.671,"posy":1.671,"posz":1.671,"stat":4}} [g2]
    g2: <-C--1467999867817---- {"sr":{"posx":1.631,"posy":1.631,"posz":1.631,"stat":4}} [g2]
    g2: <-C--1467999868067---- {"sr":{"posx":1.592,"posy":1.592,"posz":1.592,"stat":4}} [g2]
    g2: <-C--1467999868318---- {"sr":{"posx":1.552,"posy":1.552,"posz":1.552,"stat":4}} [g2]
    g2: <-C--1467999868569---- {"sr":{"posx":1.513,"posy":1.513,"posz":1.513,"stat":4}} [g2]
    g2: <-C--1467999868820---- {"sr":{"posx":1.474,"posy":1.474,"posz":1.474,"stat":4}} [g2]
    g2: <-C--1467999869072---- {"sr":{"posx":1.434,"posy":1.434,"posz":1.434,"stat":4}} [g2]
    g2: <-C--1467999869323---- {"sr":{"posx":1.394,"posy":1.394,"posz":1.394,"stat":4}} [g2]
    g2: <-C--1467999869573---- {"sr":{"posx":1.355,"posy":1.355,"posz":1.355,"stat":4}} [g2]
    g2: <-C--1467999869824---- {"sr":{"posx":1.316,"posy":1.316,"posz":1.316,"stat":4}} [g2]
    g2: <-C--1467999870076---- {"sr":{"posx":1.276,"posy":1.276,"posz":1.276,"stat":4}} [g2]
    g2: <-C--1467999870327---- {"sr":{"posx":1.236,"posy":1.236,"posz":1.236,"stat":4}} [g2]
    g2: <-C--1467999870579---- {"sr":{"posx":1.197,"posy":1.197,"posz":1.197,"stat":4}} [g2]
    g2: <-C--1467999870830---- {"sr":{"posx":1.157,"posy":1.157,"posz":1.157,"stat":4}} [g2]
    g2: <-C--1467999871082---- {"sr":{"posx":1.118,"posy":1.118,"posz":1.118,"stat":4}} [g2]
    g2: <-C--1467999871333---- {"sr":{"posx":1.078,"posy":1.078,"posz":1.078,"stat":4}} [g2]
    g2: <-C--1467999871583---- {"sr":{"posx":1.039,"posy":1.039,"posz":1.039,"stat":4}} [g2]
    g2: <-C--1467999871834---- {"sr":{"posx":0.999,"posy":0.999,"posz":0.999,"stat":4}} [g2]
    g2: <-C--1467999872085---- {"sr":{"posx":0.960,"posy":0.960,"posz":0.960,"stat":4}} [g2]
    g2: <-C--1467999872337---- {"sr":{"posx":0.920,"posy":0.920,"posz":0.920,"stat":4}} [g2]
    g2: <-C--1467999872589---- {"sr":{"posx":0.880,"posy":0.880,"posz":0.880,"stat":4}} [g2]
    g2: <-C--1467999872840---- {"sr":{"posx":0.841,"posy":0.841,"posz":0.841,"stat":4}} [g2]
    g2: <-C--1467999873092---- {"sr":{"posx":0.801,"posy":0.801,"posz":0.801,"stat":4}} [g2]
    g2: <-C--1467999873343---- {"sr":{"posx":0.762,"posy":0.762,"posz":0.762,"stat":4}} [g2]
    g2: <-C--1467999873596---- {"sr":{"posx":0.722,"posy":0.722,"posz":0.722,"stat":4}} [g2]
    g2: <-C--1467999873846---- {"sr":{"posx":0.683,"posy":0.683,"posz":0.683,"stat":4}} [g2]
    g2: <-C--1467999874097---- {"sr":{"posx":0.643,"posy":0.643,"posz":0.643,"stat":4}} [g2]
    g2: <-C--1467999874348---- {"sr":{"posx":0.604,"posy":0.604,"posz":0.604,"stat":4}} [g2]
    g2: <-C--1467999874598---- {"sr":{"posx":0.565,"posy":0.564,"posz":0.564,"stat":4}} [g2]
    g2: <-C--1467999874849---- {"sr":{"posx":0.525,"posy":0.525,"posz":0.525,"stat":4}} [g2]
    g2: <-C--1467999875100---- {"sr":{"posx":0.486,"posy":0.486,"posz":0.486,"stat":4}} [g2]
    g2: <-C--1467999875351---- {"sr":{"posx":0.446,"posy":0.446,"posz":0.446,"stat":4}} [g2]
    g2: <-C--1467999875603---- {"sr":{"posx":0.406,"posy":0.406,"posz":0.406,"stat":4}} [g2]
    g2: <-C--1467999875853---- {"sr":{"posx":0.367,"posy":0.367,"posz":0.367,"stat":4}} [g2]
    g2: <-C--1467999876104---- {"sr":{"posx":0.328,"posy":0.328,"posz":0.328,"stat":4}} [g2]
    g2: <-C--1467999876355---- {"sr":{"posx":0.288,"posy":0.288,"posz":0.288,"stat":4}} [g2]
    g2: <-C--1467999876606---- {"sr":{"posx":0.249,"posy":0.249,"posz":0.249,"stat":4}} [g2]
    g2: <-C--1467999876858---- {"sr":{"posx":0.209,"posy":0.209,"posz":0.209,"stat":4}} [g2]
    g2: <-C--1467999877108---- {"sr":{"posx":0.170,"posy":0.170,"posz":0.170,"stat":4}} [g2]
    g2: <-C--1467999877359---- {"sr":{"posx":0.130,"posy":0.130,"posz":0.130,"stat":4}} [g2]
    g2: <-C--1467999877610---- {"sr":{"posx":0.091,"posy":0.091,"posz":0.091,"stat":4}} [g2]
    g2: <-C--1467999877861---- {"sr":{"posx":0.051,"posy":0.051,"posz":0.051,"stat":4}} [g2]
    g2: <-C--1467999878114---- {"sr":{"posx":0.012,"posy":0.012,"posz":0.012,"vel":14.44,"stat":4}} [g2]
    g2: <-C--1467999878361---- {"sr":{"posx":0.000,"posy":0.000,"posz":0.000,"vel":0.00,"stat":4,"line":0}} [g2]

**Comment by jlucidar** [comment]
It seems to be fixed, I did follow your explanation and was not able to reproduce the bug.
please reopen the issue if it happens again.
