### ISSUE TITLE
Cannot create SBP jobs through the editor

### ISSUE THREAD

**Issue by Alex-Canales** [FabMo/FabMo-Engine#491]
In the Editor, chose OpenSBP. Put:

    SA
    MH
    M2 1, 1

``Submit as Job``, save the file as ``editor.sbp``. In job manager, run it: the job manager shows it as "running job" but in fact launches the next job. Impossible to remove the job as "running job", need to kill the engine.

Logs when trying to run the job without another one pending:

    info: Running the next job in the queue [routes]
    info: Arming the machine for nextJob [machine]
    info: Firing automatically since authorization is disabled. [machine]
    info: Machine is deauthorized. [machine]
    info: Running next job [machine]
    info: printing[object Object] [db]
    info: 158 [db]
    info: [object Object] [machine]
    info: Running job {"file_id":7,"name":"OpenSBP (Editor)","description":"An OpenSBP job from the editor","created_at":1469801581305,"started_at":1469801585616,"finished_at":null,"state":"running","order":null,"_id":158} [machine]
    info: Running file /opt/fabmo/files/ad4fa410-5593-11e6-b179-f3de04960557.nc [machine]
    info: Got a machine state change: idle [machine]
    info: Connected G-Code Runtime [gcode]
    debug: Saving config to /opt/fabmo/config/instance.json [config]
    error: 102,STAT_BAD_NUMBER_FORMAT,number format error [machine]
    error: 102,STAT_BAD_NUMBER_FORMAT,number format error [machine]
    error: 132,STAT_MCODE_COMMAND_UNSUPPORTED,M command is not supported [machine]
    debug: GET /jobs/queue [engine]
    debug: GET /jobs/history?start=0&count=10 [engine]
    debug: fsync()ed /opt/fabmo/config/instance.json [config]

Sometimes the logs are:

    info: Running the next job in the queue [routes]
    info: Arming the machine for nextJob [machine]
    info: Firing automatically since authorization is disabled. [machine]
    info: Machine is deauthorized. [machine]
    info: Running next job [machine]
    info: printing[object Object] [db]
    info: 159 [db]
    info: [object Object] [machine]
    info: Running job {"file_id":7,"name":"OpenSBP (Editor)","description":"An OpenSBP job from the editor","created_at":1469801726333,"started_at":1469801729343,"finished_at":null,"state":"running","order":null,"_id":159} [machine]
    info: Running file /opt/fabmo/files/ad4fa410-5593-11e6-b179-f3de04960557.nc [machine]
    info: Got a machine state change: idle [machine]
    info: Connected G-Code Runtime [gcode]
    debug: Saving config to /opt/fabmo/config/instance.json [config]
    error: 102,STAT_BAD_NUMBER_FORMAT,number format error [machine]
    error: 102,STAT_BAD_NUMBER_FORMAT,number format error [machine]
    error: 132,STAT_MCODE_COMMAND_UNSUPPORTED,M command is not supported [machine]
    debug: POST /jobs/queue/run [engine]
    info: Running the next job in the queue [routes]
    debug: GET /jobs/queue [engine]
    debug: GET /jobs/history?start=0&count=10 [engine]
    debug: fsync()ed /opt/fabmo/config/instance.json [config]
    error: Error: No pending jobs.
        at Machine.<anonymous> (/home/alex/Shopbot/Engine/machine.js:607:13)
        at /home/alex/Shopbot/Engine/node_modules/tingodb/lib/tcursor.js:305:4
        at _fnApply (/home/alex/Shopbot/Engine/node_modules/safe/lib/safe.js:172:22)
        at _catcher (/home/alex/Shopbot/Engine/node_modules/safe/lib/safe.js:349:11)
        at /home/alex/Shopbot/Engine/node_modules/safe/lib/safe.js:462:4
        at _wrapArgsSure (/home/alex/Shopbot/Engine/node_modules/safe/lib/safe.js:203:15)
        at Object.async.eachSeries (/home/alex/Shopbot/Engine/node_modules/tingodb/node_modules/async/lib/async.js:142:20)
        at /home/alex/Shopbot/Engine/node_modules/tingodb/lib/tcursor.js:298:9
        at _fnApply (/home/alex/Shopbot/Engine/node_modules/safe/lib/safe.js:172:22)
        at _catcher (/home/alex/Shopbot/Engine/node_modules/safe/lib/safe.js:349:11)
        at /home/alex/Shopbot/Engine/node_modules/safe/lib/safe.js:462:4
        at _wrapArgsSure (/home/alex/Shopbot/Engine/node_modules/safe/lib/safe.js:218:14)
        at Immediate.<anonymous> (/home/alex/Shopbot/Engine/node_modules/safe/lib/safe.js:272:23)
        at runCallback (timers.js:570:20)
        at tryOnImmediate (timers.js:550:5)
        at processImmediate [as _immediateCallback] (timers.js:529:5) [routes]
    debug: GET /jobs/queue [engine]

Note: there is no issue when submitting a SBP file. The issue is only when the file is created by the editor.

**Comment by ryansturmer** [comment]
Are you selecting OpenSBP as the language when you are using the editor?  Does the syntax hilighting for the job look normal?

![screen shot 2016-08-08 at 11 21 14 am](https://cloud.githubusercontent.com/assets/1383181/17484991/4cbe19e6-5d5a-11e6-92ce-91e7f3a0d28e.png)

**Comment by Alex-Canales** [comment]
Yes, I did select OpenSBP, the syntax looked normal.

**Comment by ryansturmer** [comment]
@Alex-Canales this is definitely the job being submitted as a g-code file instead of an SBP file somehow.  Can you provide specific steps to reproduce?

**Comment by ryansturmer** [comment]
This appears not to be the case in the latest RC.  I am going to close it for now, and we can re-open in the event that it turns up again.
