### ISSUE TITLE
SBP Files "skipping to the end"

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#497]
Such a file is attached.  Run and the spindle cuts off after it stops and then jogs home.
[circuit boards.txt](https://github.com/FabMo/FabMo-Engine/files/407082/circuit.boards.txt)

**Comment by SW0rden** [comment]
I've run this to completion a couple of time on my machine.  The only issue I had was that I don't have Macro C7 installed, but I just ignored it and it parked and shut off the spindle.  Don't see anything in the code that would cause a problem.

![circuit board cut](https://cloud.githubusercontent.com/assets/18059548/17487400/3cf30486-5d5a-11e6-8429-fe11648ec2e0.jpg)
