### ISSUE TITLE
Connection lost in AP mode with release Candidate

### ISSUE THREAD

**Issue by wlyoung** [FabMo/FabMo-Engine#517]
Updated to the release candidate and updated the firmware. If I  switch to AP mode I get the login screen and  everything works fine the first time, but if I shut down and restart I don't get the login and can only connect to the updater. The console display shows that it's connected but shell only says "hooks" with none of teh usual stream of chatter. It seems to work correctly when connected to a local network

**Comment by ryansturmer** [comment]
@wlyoung , can you retrieve the contents of the /opt/fabmo/logs directory from your tool?
