### ISSUE TITLE
preview displays extra line

### ISSUE THREAD

**Issue by jw4rd** [FabMo/FabMo-Engine#531]
The extra line is not shown when the preview animation is active.

g20
g0z0.25
g0x0y0
g1z-0.125f30
g1x1y0f30
g0z0.25
m30

**Comment by Alex-Canales** [comment]
Which extra line are you talking about?

**Comment by jw4rd** [comment]
the line from x0z0 to x1z-0.125

**Comment by Alex-Canales** [comment]
If you are talking about the extra line that should be displayed where I circled, this is normal. The line for the G-Code and the line for the Z axis overlap, therefore only the line for the Z axis is displayed.
![extra line](https://cloud.githubusercontent.com/assets/12187544/19525678/0d3d17bc-9622-11e6-811a-cd854a7a13aa.png)

**Comment by jw4rd** [comment]
![line](https://cloud.githubusercontent.com/assets/14109891/19525888/1846df9c-95e8-11e6-9616-c22dd8d2fa8d.png)

**Comment by Alex-Canales** [comment]
OK, I was using the stand alone viewer app for testing your code. The viewer app in FabMo Engine is maybe not the more recent version. I will update and test it as soon as possible.
