### ISSUE TITLE
Network Switch Farewell Message

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#545]
Fabmo.js needs to provide a way to confirm a deliberate disconnect with a message.  When a tool changes networks, it's jarring not to have any confirmation that it's going off the network. When you change networks using the network manager, the "last act" of the dashboard should be to throw up a dialog that indicates what network the tool is moving to and that the connection on _this_ network is well and truly lost.

**Comment by jlucidar** [comment]
added those message :
- "you're tool is now away, please use the Tool Minder to find it on the new network called name ."
- "you're tool is now back in AP mode." when joining AP mode.

let me know if you have better suggestions
