### ISSUE TITLE
Configuration app usability

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#551]
Configuration app should indicate when a value has been changed, perhaps by turning text entry boxes green once their value has been accepted.  It should also commit the last value entered before leaving the app, if possible.

**Comment by jlucidar** [comment]
@ryansturmer : 
The first part is implemented, it will also turn red, if the engine rejects the value (it does not right now but I suppose it will with the configuration refactoring).
The last point you mentioned does not seems to be possible. I tried using [this method](http://www.w3schools.com/jsref/event_onunload.asp) but it seems really browser dependent, and does not work well with backbone and Iframes.
