### ISSUE TITLE
Speed settings: G2 vs SBP we may need to consider a different way of rep speed settings

### ISSUE THREAD

**Issue by gordonab** [FabMo/FabMo-Engine#56]
There is a fundamental difference between the way G-code and G2 take speed settings and the way ShopBot does. It may make more sense to add some additional commands to the VS command for the sake of G2 for setting the maximum settings. G2 uses maximum feed and rapids, then takes an F command to set the current speed. ShopBot jog speeds are used in the same way as the maximum rapid, but maximum feedrate is used differently. Anyone have any thoughts on this?

**Comment by ryansturmer** [comment]
I think this has been hashed out.
