### ISSUE TITLE
Something in the latest dev has killed my engine

### ISSUE THREAD

**Issue by SW0rden** [FabMo/FabMo-Engine#564]
Had to back up to the release version to get it back online.  The dev release just before the last also had a pulse/tick in the motors as you moved them with the keypad.  Sorry, but I don't know what version had the tick, but it was the one that was up late in the day 12/16.  The one today 12/17 kills my engine. That one would be v1.4.2-g4e28979-dev.fmp

**Comment by wholetthedogsout** [comment]
Fixed. It was an out of place dependency.

**Comment by SW0rden** [comment]
Thanks, back online!
