### ISSUE TITLE
Motor tick or pulse with v1.4.2-ga7af21d-dev

### ISSUE THREAD

**Issue by SW0rden** [FabMo/FabMo-Engine#570]
v1.4.2-ga7af21d-dev has a noticeable pulse in motion on all axes.  Please test this on a Desktop/Max, as you won't have enough travel to hear/feel it on the small envelope of a HandiBot.

While using the keypad to move an axis, you can hear/feel a distinct 'bump----bump----bump... as it travels.  Reinstalling the v1.4.2 release version with it's firmware removes it.

**Comment by SW0rden** [comment]
Anyone have a chance to verify this?

**Comment by ryansturmer** [comment]
Yes, this has been resolved, but the fix is entangled with some other issues we're working on.  Should have a release for this soon.

**Comment by SW0rden** [comment]
Thanks for the update Ryan.
