### ISSUE TITLE
Apps don't install in master

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#578]
![screen shot 2017-01-16 at 10 50 37 am](https://cloud.githubusercontent.com/assets/1383181/21989645/af915710-dbd9-11e6-9181-1abdc16291fe.png)

**Comment by wholetthedogsout** [comment]
what app are you installing @ryansturmer?

**Comment by ryansturmer** [comment]
jk, @jlucidar fixed this and I hadn't webpacked the update.

**Comment by jlucidar** [comment]
This have been fixed recently by d8ba397c3cf926a4ba485982df7798278903d6c2
