### ISSUE TITLE
Can't start a job from Job Manager on mobile in latest master branch

### ISSUE THREAD

**Issue by jlucidar** [FabMo/FabMo-Engine#580]
The "click" event is not triggered when pressing the green arrow in the Job Manager on a touchscreen. Happening on my Android nexus5 using chrome and on the iPad using safari and chrome. works fine on computer.

**Comment by jlucidar** [comment]
@wholetthedogsout : it seems to be related to your recent commit 53e595836e73302addfde4efebf25a35364ecefd .

**Comment by wholetthedogsout** [comment]
Thanks Jimmy, yeah I know what it is.

**Comment by wholetthedogsout** [comment]
That should fix it

**Comment by jlucidar** [comment]
it worked ! thanks @wholetthedogsout .
