### ISSUE TITLE
fabmo unusable 

### ISSUE THREAD

**Issue by goboldgraphics** [FabMo/FabMo-Engine#651]
installed Fabmo on raspberry pi 3, there are no DRO or jog arrows the only part that works for me is when i send a Gcode to the editor and submit. Also the remote when click on appears and disappears immediately. At some point, it did work but stayed stuck and would not leave manual mode without hard reset. Thank you in advance
![screenshot_2](https://user-images.githubusercontent.com/37946442/38158878-d612cbcc-346a-11e8-97c3-ae92802621ab.jpg)

**Comment by ryansturmer** [comment]
The manual controls have been moved to the left sidebar, under the joypad control.

It looks like your input polarities are set incorrectly from your screenshot - try going in the configuration and reversing them, the softwaremay be interpreting an input as a cancel button press, which is dismissing the dialog immediately.
