### ISSUE TITLE
v1.6.3 top bar/panel issue

### ISSUE THREAD

**Issue by SW0rden** [FabMo/FabMo-Engine#654]
Top panel or whatever you call it is, well, expanded or something on all pages (see attached).
Keypad is missing.
Double vertical scrollbars. 
?!?! :-( 

![v1 6 3](https://user-images.githubusercontent.com/18059548/39061472-0428962a-448a-11e8-8144-6ff811f15218.PNG)

**Comment by wholetthedogsout** [comment]
Looks like you have cached elements from the dev.  You need to refresh the url. Delete everything after the IP address in the address bar and hit enter.

**Comment by SW0rden** [comment]
Nope, did that, same way on all devices and 3 browsers.

**Comment by wholetthedogsout** [comment]
Your update must have failed then. You are definitely not getting all the files from the server. Try updating again. I just published a newer version of 1.6.3. So hopefully that will work.

**Comment by SW0rden** [comment]
Works now, thanks.
