### ISSUE TITLE
Switching between Inches & Millimeters

### ISSUE THREAD

**Issue by Zup2018** [FabMo/FabMo-Engine#655]
How do I switch between inches and millimeters in Grbl Control? In CamBam I profiled a 4.25" cutout, but when I start the program, it cuts the profile approx. .425" so I'm thinking if thinks I'm using millimeters when I wan to use inches. Thanks!

Zup2018

**Comment by ryansturmer** [comment]
I'm betting this isn't an inch vs mm issue if it's off by 10x - what kind of tool are you running?
