### ISSUE TITLE
Some macros not working in 1.7.X

### ISSUE THREAD

**Issue by SW0rden** [FabMo/FabMo-Engine#680]
The Zzero and Homing macros do not execute.  My Zzero macro is one from some time back, edited for my machine and has worked fine until the 1.7.X release.  The homing macro is stock and does nothing as well.

Macro attached.
[Fabmo Zzero Macro.txt](https://github.com/FabMo/FabMo-Engine/files/2462340/Fabmo.Zzero.Macro.txt)

**Comment by ryansturmer** [comment]
Scott - there has been a syntax change in the language - it should have thrown an error, but didn't which is a bug we're working on.  `END "Message"` has been replaced with `FAIL "Message"` - END no longer supports the message argument.

Change the lines that say `END "Message"` to  `FAIL "Message"` and it should work.  We'll work to get the error properly reported.
