### ISSUE TITLE
Dashboard appears to "hang" and stop getting updates

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#73]
In certain browsers, at least MSIE 9/10 as well as some versions of chrome for android, the dashboard can get into a state where no updates are recieved from the server, and a false position is displayed.  You must exit chrome (or close the tab) and reopen the dashboard URL to recover normal operation.

**Comment by jlucidar** [comment]
did you try that with the websocket version ?

**Comment by ryansturmer** [comment]
No, but I am looking at this now, with the intent to switch over if it works OK

**Comment by ryansturmer** [comment]
This still seems to be an issue, particularly where there is a loss of internet connection.  I think a more robust reconnection strategy with socket.io might be in order.
