### ISSUE TITLE
Improve the pause dialog so that the "quit" / "resume"  buttons are programmatically specified, and the response returned to the program.

### ISSUE THREAD

**Issue by RobMackie** [FabMo/FabMo-Engine#756]
We want to be able to selectively present the user with a quit button only. or an OK button.

Right now we frequently have "quit" and "resume" buttons presented but resume does nothing different from quit.

**Comment by RobMackie** [comment]
Closed with PR #759 merge

**Comment by RobMackie** [comment]
closed by accident

**Comment by jkeppeler-parthenon** [comment]
addressed in PR #762

**Comment by RobMackie** [comment]
Done and example provided by josh was used to test it. The exmaple is explained in the text of issue pr #762
