### ISSUE TITLE
Running shopbot logo file from editor, Stop/Quit, re-run shopbot logo file again - fails to cut

### ISSUE THREAD

**Issue by RobMackie** [FabMo/FabMo-Engine#773]
Doing Dev Checks step 1. Running shopbot logo file from editor

Runs fine. 
Stop/resume multiple times is fine
Stop/quit works, BUT if you try to run the file a second time, the file starts but never gets to moving the cutting head, and silently ends prematurely.

A good fix for this would leave the machine in a state where it could run a "next file" after a "last file" was run through "stop/quit"

Here is a much simpler version of the same problem.
SA
m2, 0,0
mx, 5
'test pause
pause
my, 5
m2, 0,0
end

hit stop/quit on a first run, then run it a second time. the pause dialog never displays and the file is left aat x=5, y=0. 

* running the file again works - it recovers by the 2nd attempt to rerun the file.
** quitting from the pause dialog does not cause the problem.  Quitting from the footer does cause the problem. Again, the problem isn't visible until the run of the file that immediately follows the run that was subjected to stop/quit. And after the run that fails, future runs will succeed, until another stop/quit is performed. Then the very next iteration will fail again.
*** this may be related to #767 but does appear to be independent

**Comment by RobMackie** [comment]
This turns out to be a duplicate of the more completely analyzed issue #769 
This case should be tested after a fix to #769 but the details on that issue are  more useful for debugging.

**Comment by jkeppeler-parthenon** [comment]
corrected in PR #788

**Comment by RobMackie** [comment]
Closeed with PR #788
