### ISSUE TITLE
SBP Language Variable Used but not defined results in popup the first time and hangs fabmo the 2nd or 3rd time.

### ISSUE THREAD

**Issue by RobMackie** [FabMo/FabMo-Engine#782]
Detaiils in this google spreadsheet because images included
https://docs.google.com/spreadsheets/d/1pEXD0ROVkW0lU6GMYZGgg3_2Z6hLNGWLuUp6CrB8uq4/edit?usp=sharing

**Comment by jkeppeler-parthenon** [comment]
corrected in PR #788

**Comment by RobMackie** [comment]
Hang resolved by PR #788
