### ISSUE TITLE
Footer Stop button hidden after Error report

### ISSUE THREAD

**Issue by jkeppeler-parthenon** [FabMo/FabMo-Engine#789]
In editor, after an error occurs in an opensbp file and is reported through the error modal on next run fromt he editor the stop footer remains hidden.

A browser reload will reset and the footer will correctly be shown on run.

**Comment by jkeppeler-parthenon** [comment]
Fix in PR #794  Assigning to Rob for code review/tests/merge.

**Comment by RobMackie** [comment]
resolved with pull request #794  
Test results on the PR record.
