### ISSUE TITLE
gcode runtime feedhold from software "STOP" can not be resumed sometimes

### ISSUE THREAD

**Issue by RobMackie** [FabMo/FabMo-Engine#792]
In the gcode runtime, if "STOP" in the footer is clicked, then motion stops. Some times (pretty frequently) the resume/quit display disappears and the "STOP" footer returns with no user intervention. When this happens, the job does not resume and if the  user clicks "STOP" the infinite spinny arrow happens, and if the user doesn't hit stop, nothing happens. 

The condition only seems to happen on the first "STOP" of a job and doesn't always happen. If it doesn't happen on the first feedhold, it seems not to happen for the duration of that job, regardless of how many feedholds are exectuted.

Work around - use the escape key to send a "kill" '!' to g2core. The job aborts and one can then restart the job.

**Comment by jkeppeler-parthenon** [comment]
![stop-bug](https://user-images.githubusercontent.com/73194707/152027017-791ed2cf-7ca7-4b27-a5cd-2ea8edcea449.png)
Issue seems to be this "jiggerypokery" triggering

**Comment by kyle-kingsbury** [comment]
Fixed with https://github.com/FabMo/FabMo-Engine/pull/846. Related to stat 3 causing programs to end early.
