### ISSUE TITLE
VU Command modifications

### ISSUE THREAD

**Issue by gordonab** [FabMo/FabMo-Engine#83]
The parameters in the VU command have been reordered so that they make more sense and are easier to enter. This also removes some of the SB3 specific and obsolete parameters from the list. This command is now channelcentric instead of being based on axes. This should help make axes reassignment work better.

The new list is: VU, 1unitVal, 2unitVal, 3unitVal, 4unitVal, 5unitVal, 6unitVal, 1multiply, 2multiply, 3multiply , 4multiply, 5multiply, 6multiply

Multiplier settings for each of the channels are only stubbed in. They won't do anything until G2 supports resolution gear shifting.

**Comment by ryansturmer** [comment]
When we make changes like this, we're going to have to update the PRM file as well.  It still exists, and does drive the command interpreter.  What used to be the cmd/prm file is now a single JSON file here: 

https://github.com/ShopBotTools/FabMo-Engine/blob/master/runtime/opensbp/sb3_commands.json#L3641-L3854

(Hilighted for the VU section) - We could probably write a little tool for this that turns that file into some documentation.
