### ISSUE TITLE
Input generated feed hold as an interrupt (or don't resume is feedhold button if current held down)

### ISSUE THREAD

**Issue by kyle-kingsbury** [FabMo/FabMo-Engine#841]
Currently our input feedhold is initiated on the leading edge of the input signal, then resumed with the resume button. Even with the button held down, you can resume the program. Through discussion we have decided that interrupt behavior may be beneficial especially in a classroom setting. i.e. the machine will not resume if the input button is being held down. The remote controlled nature of  FabMo makes this especially important.

**Comment by RobMackie** [comment]
I'm wondering if the word "interrupt" is being overloaded or misused here. I think the point of this issue is that there is some value to ignoring/refusing a "resume" if the resume is presented at a time when the "feedhold button" is in the "depressed" state.
