### ISSUE TITLE
Broken margins on fieldsets in configuration apps (mobile)

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#91]
![screenshot_2015-04-16-16-06-44](https://cloud.githubusercontent.com/assets/1383181/7214043/4e870e5a-e564-11e4-8b3f-3aca6053344a.png)

There should be margins there, but for midsize and below there aren't.  Either the fieldset needs margins or the labels need to come in some.

**Comment by jlucidar** [comment]
not happening anymore. closed
