### ISSUE TITLE
Authorize: Spindle keeps spinning while dialog is on screen

### ISSUE THREAD

**Issue by kyle-kingsbury** [FabMo/FabMo-Engine#915]
Since this is a safety feature, the spindle should not be running when the user is prompted for authorization.

**Comment by kyle-kingsbury** [comment]
This may be acceptable behavior, need to discuss further.

**Comment by RobMackie** [comment]
Possible variant is pause with feedhold parameter as opposed to pause with timer as we have now or pause with human prompt.

all 3 could coexist.

**Comment by RobMackie** [comment]
investigate if still relevant

**Comment by RobMackie** [comment]
We are going to depend on the user to write the file correctly. Bug closed as not a bug.
