### ISSUE TITLE
App icons are dumb in app manager on mobile

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#92]
The app icons get squished in mobile.  They should be hidden in mobile, or something.  Maybe switch to datatables with an expandable detail subrow.

![screenshot_2015-04-16-16-03-54](https://cloud.githubusercontent.com/assets/1383181/7214045/8e88d5c4-e564-11e4-933e-8ffaea65afbb.png)

**Comment by wholetthedogsout** [comment]
Can't recreate this in a browser @ryansturmer is this still an issue?

**Comment by ryansturmer** [comment]
I will look into this shortly.

**Comment by ryansturmer** [comment]
This one actually is gone! :)
