### ISSUE TITLE
 Top bar display on mobile

### ISSUE THREAD

**Issue by ryansturmer** [FabMo/FabMo-Engine#96]
Currently on mobile there is no top-bar display, but there's plenty of room.  We should have at least the running state (maybe stop pause controls) and tool position there.
![screenshot_2015-04-16-16-06-31](https://cloud.githubusercontent.com/assets/1383181/7214068/1d8e7804-e566-11e4-8412-fb37bce346c8.png)

**Comment by jlucidar** [comment]
do we still want the status displayed there ? If not, this is closed.

**Comment by ryansturmer** [comment]
Nope
