### ISSUE TITLE
Distorted cut of OpenSBP project (missed steps?)

### ISSUE THREAD

**Issue by RobMackie** [FabMo/FabMo-Engine#966]
Overview: Cutting a part - sometimes it cuts perfectly - 2 times it has been distorted. It does not seem likely that it's a workholding problem but this can not be eliminated as a possibility - but it could also be a firmware problem.

Details - Monday June 27, I updated the desktop max machine in Tyler's work area that runs FabMo with the latest off master. (will get the hash and put it here soon. I think it was: v3.1.38 with current g2 firmware. Having upgraded using /home/pi/Scripts/dev-build.sh, i launched the browser on the pi (keyboard,mouse and monitor attached) and picked the Desktop profile and set debug to g2 and turned off the authorization feature, and ran macro#201  (I do not remember if i then used macro#3 (c3) to home tool or not)

Lead up - I had noticed that things were going slowly and that the file system was at 90% utilization, so I logged into pi with a keyboard, mouse and monitor and accessed the "expand file system" option from raspi-config. Then rebooted the pi for that to complete. 

Then I pulled out my laptop and connected to the infrastructure wifi at shopbot to get to the tool which is attached to that infrastructural network by ethernet.  

Then I scheduled a cut of the opensbp file I'll attach here. (bnc-connector.sbp) It's an arbitrary file I used for testing.  I then used the keyboard popup and mouse to position the tool and set x and y zero by hitting the "zero" buttons on the axes in the manual control dialog. Then i moved the tool head over an empty part of the spoilboard and used the C2 and the probe to set z-zero to the surface of the bed.

I ran the cut from my laptop. It failed to cut all the way through. I set z-zero to be 0.1mm lower and ran it again without adjusting x or y zero.  It cut free. (tabs cut away - tabs on that file were not tall enough to work)

I didn't examine the part carefully at that time. I moved the x and y zero over with the manual keypad to another empty piece of the stock (1/8" aluminum) and cut again. This time there was no need to reset the z-zero, so it cut free the first time.

At this point, I examined both pieces. Both showed significant drift between layers.  I then moved x & y zero and cut multiple pieces all of which came out without any problem at all.

Will attach the file and photos soon.

**Comment by kyle-kingsbury** [comment]
Fixed after PR https://github.com/FabMo/FabMo-G2-Core/pull/65
