### ISSUE TITLE
USB IP retrieval interferes with loading file from USB drive

### ISSUE THREAD

**Issue by kyle-kingsbury** [FabMo/FabMo-Engine#980]
If a user has a cut file on a USB drive that they want to upload, and they also have network.txt or shopbotsupport.txt on the same USB drive, the USB may eject before the file has a chance to load.

**Comment by RobMackie** [comment]
If using usb for file transfer and running browser on the pi, you can not have any of the trigger files (network.txt etc) on the usb thumb  because they cause an "auto - eject" after writing their data to the thumb drive.
